### ISSUE TITLE
No Separate Variables for Persistent and Non-Persistent Datastores on vSphere cpi.yml

### ISSUE THREAD

**Issue by phong2tran** [cloudfoundry/bosh-deployment#103]
Currently we can only specify one datastore for both persistent and non-persistent datastores for vSphere CPI (https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/cpi.yml) through vcenter_ds variable.

datastore_pattern: ((vcenter_ds))
persistent_datastore_pattern: ((vcenter_ds))

If we 2 separate datastores for persistent and non-persistent disks, it's not possible to use the bosh-deployment for this scenario unless further modifications are done to the cpi.yml file. 

Can we change to use 2 variables vcenter_ds and vcenter_pds (persistent-datastore) in cpi.yml of bosh-deployment project?

**Comment by cppforlife** [comment]
@phong2tran recommend way is to add a custom ops file that configures additional things.

**Comment by phong2tran** [comment]
ok I will use the ops file to configure the additional datastore. Thanks @cppforlife!
