### ISSUE TITLE
README's instructions assume deploying to a local-only network -- is this intentional?

### ISSUE THREAD

**Issue by cjcjameson** [cloudfoundry/bosh-deployment#126]
Hi there,

We're targeting AWS, and using `bosh create-env` to get a non-prod environment, and so we're heavily inspired by https://github.com/cloudfoundry/bosh-deployment#sample-installation-instructions

It seems like these instructions are assuming you have access to 10.0.0.6 where the Director gets deployed, either via VPN or you're already in the network somehow. Are we reading this correctly? cc/ @goutamtadi1

Perhaps the default use case you're showing assumes that the user would add more networking infrastructure, like a public load balancer or something, to route traffic into the private IP address for the Director?

In our case, we want to let AWS assign the bosh director VM an elastic IP, and then rely on security groups to allow access over a limited number of ports. DNS etc. is not an immediate concern.

We think the solution is to

1. pre-provision the elastic IP
2. add a network to https://github.com/cloudfoundry/bosh-deployment/blob/b1f8d1bfa95fee6c8b89c678781e94912c41b31a/bosh.yml#L23-L30

```
- name: public
  type: vip
```

3. put the given elastic IP address in at https://github.com/cloudfoundry/bosh-deployment/blob/b1f8d1bfa95fee6c8b89c678781e94912c41b31a/bosh.yml#L43-L45 as a new network for the job:

```
    - name: public
      static_ips: [101.102.103.104]
```

We're happy to write our own ops-file to layer those elements on, but we just want to make sure we're not missing something. Thanks!

**Comment by cppforlife** [comment]
@cjcjameson thinking is to have a jumpbox (something like this: https://github.com/cppforlife/jumpbox-deployment) that is accessible over a public ip or a vpn (https://github.com/dpb587/openvpn-bosh-release). once that's configured, you can tunnel through that to install your director and other deployments.
