### ISSUE TITLE
README edge-case: --ca-cert from `<(bosh int)` doesn't work if BOSH_LOG_LEVEL=DEBUG

### ISSUE THREAD

**Issue by cjcjameson** [cloudfoundry/bosh-deployment#128]
If you are trying to run the command from the README:

```
bosh -e 10.0.0.6 --ca-cert <(bosh int ./creds.yml --path /director_ssl/ca) alias-env bosh-1
```

And get the error:

```
[CLI] 2017/08/22 09:55:20 ERROR - Validating Director connection config: Parsing certificate 2: Missing PEM block
Validating Director connection config:
  Parsing certificate 2: Missing PEM block

Exit code 1
```

Check your BOSH_LOG_LEVEL -- if it's "DEBUG" then the process-substitution in the shell command won't quite work because the output has extra lines

**Comment by cjcjameson** [comment]
Closing as it's just an fyi -- too much of an edge case to be in the readme itself.

**Comment by dpb587-pivotal** [comment]
@cppforlife, I think logger should be sending output to STDERR instead of STDOUT. Objections? I think it's more correct, and would also happen to fix this particular scenario.

**Comment by dpb587-pivotal** [comment]
Actually, closing in favor of https://github.com/cloudfoundry/bosh-cli/issues/301
