### ISSUE TITLE
GCP authentication issue

### ISSUE THREAD

**Issue by igor-fomenko** [cloudfoundry/bosh-deployment#135]
Have the following error when uploading stemcell to bosh director:
20:41:58 | Update stemcell: Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3445.7 to the cloud (00:00:30)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL                                       : Failed to create Google Image: Post https://www.googleapis.com/compute/v1/projects/pivotal-lab/global/images?alt=json:                                        oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.141.84:443: i/o timeout' in                                        'create_stemcell' CPI method

Bosh director was created using the following command:
sudo bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/gcp/cpi.yml \
    -v director_name=bosh-concourse \
    -v internal_cidr=10.142.0.0/20 \
    -v internal_gw=10.142.0.1 \
    -v internal_ip=10.142.0.10 \
    --var-file gcp_credentials_json=~/Downloads/PivotalLab-1dafffbaeae7.json \
    -v project_id=pivotal-lab \
    -v zone=us-east1-c \
    -v tags=[internal] \
    -v network=default \
    -v subnetwork=default

I followed the procedure to create bosh director described here:http://bosh.io/docs/init-google.html

I found out that the reason for authentication error with GCP is that bosh director vm is created without external IP. Adding manually ephemeral external IP to director VM resolved the issue for me.

**Comment by cppforlife** [comment]
following linked page describes a bit more about the situation:
http://bosh.io/docs/init-external-ip.html

**Comment by igor-fomenko** [comment]
Please note that I was creating environment from GCP VM that is on the same GCP network as director, so according to documentation I did not need external IP. However I was getting this error without external IP.
The istructions here: http://bosh.io/docs/init-external-ip.html describe how to add static external IP that I did not need, so I just added ephemeral IP to resolve the situation.
It looks like external IP is required, even when initializing director from VM on the same GCP network.

**Comment by cppforlife** [comment]
> It looks like external IP is required, even when initializing director
from VM on the same GCP network.

i assume you dont have a nat box for that network?

ill try to update docs to make that clear.

**Comment by igor-fomenko** [comment]
Yes, I have no NAT box. This is probably the issue. Updating docs wold help. Thank you.
