### ISSUE TITLE
bosh director trust more than one ip

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#136]
I create a bosh lite by bosh create-env as below in my machine A(ip address 10.112.113.124). And I can access the director in my local machine by ip 192.168.50.6. Now I want to access the bosh director from another machine B, so I make a iptable nat that forward all request to port(25555) of my local machineA to 192.168.50.6:25555.  So now I can curl https://10.112.113.124:25555 successfully and get response body. But when I use bosh cli v2 to access the ip 10.112.113.124:25555 but it returns an certificate error:

Fetching info:
  Performing request GET 'https://10.121.94.103:25555/info':
    Performing GET request:
      Retry: Get https://10.121.94.103:25555/info: x509: certificate is valid for 192.168.50.6, not 10.121.94.103

Exit code 1_

**So my question is how to make my request work? The director can trust both 192.168.50.6 and 10.121.94.103?**

create env cmd:
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state ./state.json \
  -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
  -o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
  -o ~/workspace/bosh-deployment/bosh-lite.yml \
  -o ~/workspace/bosh-deployment/bosh-lite-runc.yml \
  -o ~/workspace/bosh-deployment/jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork

**Comment by mkuratczyk** [comment]
You can use https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml ops file. One of the operations it performs is to add the external IP to the certificate (see the last 3 lines).

**Comment by qibobo** [comment]
@mkuratczyk value: https://mbus:((mbus_bootstrap_password))@((external_ip)):6868, which value should provide to "mbus_bootstrap_password"?

**Comment by qibobo** [comment]
@mkuratczyk Is the following cmd right?
bosh2 create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o jumpbox-user.yml \
  -o external-ip-not-recommended.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v external_ip=10.121.94.103 \
  -v mbus_bootstrap_password=password \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork

**Comment by qibobo** [comment]
@mkuratczyk  create-env error:

Deployment state: './state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:01)
  Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-warden-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:01)
Finished validating (00:00:05)

Started installing CPI
  Compiling package 'golang_1.7/21609f611781e8586e713cfd7ceb389cee429c5a'... Finished (00:00:00)
  Compiling package 'virtualbox_cpi/e293cbbb8359fd2cbbb9777b7b91fd142ab6c688'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3445.7'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'vm-3214e91d-d282-4cf8-6523-2a2dba6e4824'... Failed (00:00:09)
  Deleting VM 'vm-3214e91d-d282-4cf8-6523-2a2dba6e4824'... Finished (00:00:01)
  Creating VM for instance 'bosh/0' from stemcell 'sc-2e82602b-9f74-4962-5e4e-f2fd3aebed11'... Failed (00:01:02)
Failed deploying (00:01:12)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-2e82602b-9f74-4962-5e4e-f2fd3aebed11':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{4273032a-00ac-45b7-4cad-153d4f865e97}}': Enabling networks: Retried '30' times: Running command: 'VBoxManage hostonlyif ipconfig vboxnet1 --dhcp', stdout: '', stderr: 'VBoxManage: error: Code NS_ERROR_NOT_IMPLEMENTED (0x80004001) - Not implemented (extended info not available)\nVBoxManage: error: Context: \"EnableDynamicIPConfig()\" at line 236 of file VBoxManageHostonly.cpp\n': exit status 1","ok_to_retry":false}

Exit code 1

**Comment by mkuratczyk** [comment]
Unfortunately I don't know why you get this error - the commands looks very similar to how I bootstrap my bosh-lite. Let's wait for the BOSH team to take a look at this error.

**Comment by dpb587-pivotal** [comment]
@qibobo, I'd recommend you deploy the VM locally without the `external-ip-not-recommended.yml` op file, but to ensure your LAN network IP is added to the director's certificate you'll need to create your own op file which looks something like...

```yaml
- type: replace
  path: /variables/name=director_ssl/options/alternative_names/-
  value: 10.112.113.124
```
 Note that changing these variable settings does not automatically generate a new certificate. You should clear out your existing settings (or remove just the `director_ssl` value from your `creds.yml`) and then re-run `create-env` with the custom op.

Once you've redeployed your director, you can try using your NAT iptables again. The advanced iptables usage is not officially supported, but should work, in theory.

**Comment by qibobo** [comment]
@dpb587-pivotal  it works. thx.
