### ISSUE TITLE
can not find the bosh-lite vm create by bosh create-env 

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#140]
I create bosh-lite in my MacOS with the cmd below. And all the deployments works well. I want to save the bosh-lite vm state, but I can not find any vms by VBoxManage list vms. Then I use ps -ef | grep VBox to find the process, they are there:

0  6677     1   0 10:55AM ??         0:03.18 /Applications/VirtualBox.app/Contents/MacOS/VBoxXPCOMIPCD
    0  6679     1   0 10:55AM ??         0:19.27 /Applications/VirtualBox.app/Contents/MacOS/VBoxSVC --auto-shutdown
    0  6736  6679   0 10:55AM ??       239:38.19 **/Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless --comment vm-f463e421-a238-481f-54e0-15bf1ef3e034 --startvm f463e421-a238-481f-54e0-15bf1ef3e034 --vrde config**
    0  6737  6679   0 10:55AM ??         0:00.50 /Applications/VirtualBox.app/Contents/MacOS/VBoxNetDHCP --ip-address 10.0.2.3 --lower-ip 10.0.2.4 --mac-address 08:00:27:1F:C9:43 --need-main on --netmask 255.255.255.0 --network NatNetwork --trunk-type whatever --upper-ip 10.0.2.254
    0  6738  6679   0 10:55AM ??         1:56.60 /Applications/VirtualBox.app/Contents/MacOS/VBoxNetNAT --ip-address 10.0.2.1 --netmask 255.255.255.0 --network NatNetwork --trunk-type whatever
  501 13877  3796   0  4:15PM ttys001    0:00.00 grep VBox

bosh create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o jumpbox-user.yml \
  -o external_ip.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork \
  -v admin_password=admin

**Comment by cppforlife** [comment]
Here is what I see on my machine for example:

```
$ VBoxManage list runningvms
"vm-2b2b0fa8-7af1-4a4a-7440-a4c5c70499b1" {2b2b0fa8-7af1-4a4a-7440-a4c5c70499b1}

$ VBoxManage list vms
"sc-6067bcb3-4de8-4043-6af4-df9b0915d7c8" {2bfcc72a-e0da-4e9e-b34c-6861fd844495}
"sc-39a5fb74-4746-43be-5196-27024fa3191a" {1adae2eb-825a-4189-b7a7-58b80efad150}
"vm-2b2b0fa8-7af1-4a4a-7440-a4c5c70499b1" {2b2b0fa8-7af1-4a4a-7440-a4c5c70499b1}
```

I would check VirtualBox UI.

**Comment by qibobo** [comment]
With all cf vms running, but vboxmanage list vms  shows nothing:
qiye@qiyedembp bosh-deployment (master) $ bosh2 -e vbox vms
Using environment '192.168.50.6' as client 'admin'


Task 117. Done

Deployment 'cf'

Instance                                          Process State  AZ  IPs           VM CID                                VM Type
api/e56bd764-3570-460b-aece-40bdbda22af7          running        z1  10.244.0.136  21eac52f-bd31-4b34-547e-7ca916b3fb20  small
blobstore/fbcf7629-4a2b-4f13-b8b0-246fc9778e9f    running        z1  10.244.0.135  b41d79d5-8b6b-4cf8-6ea2-87f989954681  small
cc-bridge/b5f1fbb6-5b6b-4bad-b69b-96b511bf31ab    running        z1  10.244.0.141  83a3031e-fe48-426f-48f0-ad92a62cdf6b  minimal
cc-clock/a404b104-dff3-4614-b961-c7cd813f04fd     running        z1  10.244.0.140  5e12ae83-b28e-4488-5272-12818e9f6a13  small
cc-worker/31a659e7-6ac4-45e5-9e07-766fc879a893    running        z1  10.244.0.137  f2a183ca-a614-410c-4027-03994d1427f1  minimal
consul/9183cd16-2d1c-4e03-a744-7a469990ec4a       running        z1  10.244.0.128  7d64c6e6-a2e1-44c8-46e9-b27878e5d4f0  minimal
diego-api/255da34d-bf2c-4e06-82a1-772ad7ae3ced    running        z1  10.244.0.133  854f8beb-24d5-492d-63e1-c518fa2c80a0  small
diego-brain/582cb89d-3787-4be8-8e56-0689b01b591d  running        z1  10.244.0.138  d42e25f1-db34-4739-5fde-23da0918e79e  minimal
diego-cell/7ecba3cc-f3b1-4bf1-8a51-732f00289f87   running        z1  10.244.0.139  132e2b8d-d04b-4bd5-6aea-d92d797da8dd  small-highmem
doppler/e79dad7d-a8a2-4220-9460-1b7b29c643b3      running        z1  10.244.0.131  d7f593bc-c2c3-4a44-79b9-4662f23ff8c0  minimal
etcd/86f015a6-3c89-451a-aa95-4e024a8419bc         running        z1  10.244.0.130  94128475-a977-4eff-66af-89f4cfdf81cf  minimal
log-api/bdf21854-69cf-4a0a-be6d-2dfc782530e4      running        z1  10.244.0.142  585ebaa0-b79a-4a44-4859-cc7ad0b91ad7  sharedcpu
nats/13ee894e-bacb-43be-868b-47c216f2cd7a         running        z1  10.244.0.129  575952e4-a7ca-4919-6486-f083779a69c6  minimal
postgres/967e415a-172d-4399-a284-ac1d9eed9306     running        z1  10.244.0.132  6b1edead-50dd-45ca-61a8-8a0beb680899  small
router/00e61891-ef23-4ec4-89f1-806bebae8d77       running        z1  10.244.0.34   2789fddb-5745-4fd1-63b7-3bd01385d920  minimal
uaa/b3c0737e-f009-4bcf-a58d-3c6810c1eeba          running        z1  10.244.0.134  2d882d5f-5cf9-4e07-5e4a-d8b6223d5ffb  minimal

16 vms

Succeeded
qiye@qiyedembp bosh-deployment (master) $ vboxmanage list vms
qiye@qiyedembp bosh-deployment (master) $

**Comment by qibobo** [comment]
uninstall virtualbox and reinstall it then the issue solved.
