### ISSUE TITLE
Invalid DNS canonical name - must begin with a letter

### ISSUE THREAD

**Issue by deltatree** [cloudfoundry/bosh-deployment#146]
Hi,

I've tried to deploy cloudfoundry to a docker based bosh installation (both current head), and I'm getting following error:

Task 219 | 12:12:42 | Preparing deployment: Preparing deployment (00:00:02)
Task 219 | 12:12:50 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 219 | 12:12:50 | Compiling packages: proxy/8c6fbff8f965520043c08d72cdf210fcd720ce26d816f23ddb90be7ca50b76e0
Task 219 | 12:12:50 | Compiling packages: tar/1de08f190630baf01c0741c86773a02f7c88c2786db1f219152e46e8853f1ccc
Task 219 | 12:12:50 | Compiling packages: busybox/eab1896633e23c0eea7e07b91b27c2c090d16efd7fe07de1adbd8e5a1b16578e
Task 219 | 12:12:50 | Compiling packages: iptables/85ef0fef60ac079fb75b36d0693cce704a662b23b0727c824f15d58713476f13
Task 219 | 12:12:50 | Compiling packages: libseccomp/0594acc533fd2801a347d6b725d0db9f3591c583d06f1e53201e701b12e09824
Task 219 | 12:12:50 | Compiling packages: apparmor/3789c10fa8ef4349f58badae51723eec7855d59b9bb6c1bb7ee21a264fae1dbb
Task 219 | 12:12:52 | Compiling packages: proxy/8c6fbff8f965520043c08d72cdf210fcd720ce26d816f23ddb90be7ca50b76e0 (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-6faf465d-7793-4352-9ce8-7eaa547cb6c5', must begin with a letter
Task 219 | 12:12:52 | Compiling packages: tar/1de08f190630baf01c0741c86773a02f7c88c2786db1f219152e46e8853f1ccc (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-bc431bff-f42d-4ad2-8cfc-b98ea04e51c2', must begin with a letter
Task 219 | 12:12:52 | Compiling packages: busybox/eab1896633e23c0eea7e07b91b27c2c090d16efd7fe07de1adbd8e5a1b16578e (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-be56fb8a-f206-4b0c-948a-fe622cf45611', must begin with a letter
Task 219 | 12:12:52 | Compiling packages: libseccomp/0594acc533fd2801a347d6b725d0db9f3591c583d06f1e53201e701b12e09824 (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-95b7e587-cb31-45eb-be0c-98501a749def', must begin with a letter
Task 219 | 12:12:52 | Compiling packages: apparmor/3789c10fa8ef4349f58badae51723eec7855d59b9bb6c1bb7ee21a264fae1dbb (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-85014a6d-09f0-4047-b6f4-1e5d5c666b5f', must begin with a letter
Task 219 | 12:12:52 | Compiling packages: iptables/85ef0fef60ac079fb75b36d0693cce704a662b23b0727c824f15d58713476f13 (00:00:02)
                    L Error: Invalid DNS canonical name '10245504-cf-compilation-89e52e3d-010a-42a7-a976-662a4bde18e0', must begin with a letter
Task 219 | 12:12:52 | Error: Invalid DNS canonical name '10245504-cf-compilation-6faf465d-7793-4352-9ce8-7eaa547cb6c5', must begin with a letter

Task 219 Started  Thu Sep 21 12:12:42 UTC 2017
Task 219 Finished Thu Sep 21 12:12:52 UTC 2017
Task 219 Duration 00:00:10
Task 219 error

Updating deployment:
  Expected task '219' to succeed but state is 'error'

Exit code 1

**Comment by dpb587-pivotal** [comment]
Hi - it looks like your deployment name maybe be using a numeric prefix which BOSH currently does not support (it's more a BOSH thing rather than a DNS thing that the message suggests). I'd recommend you try removing the numeric prefix (possibly move it to a suffix?) and try again.
