### ISSUE TITLE
When using bosh create-env with the gcp/cpi.yml and bosh-lite.yml ops files, the resulting bosh director does not accept warden stemcells

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-deployment#15]
I expect to be able to use bosh create-env with the gcp/cpi.yml and bosh-lite.yml ops files to deploy a bosh-lite to GCP.  However, the bosh director that gets deployed when using those two files includes jobs on the director for both the warden CPI and the google CPI.  When trying to upload a bosh lite stemcell, you get the error: ` Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Invalid 'warden' infrastructure' in 'create_stemcell' CPI method`.  Removing the google_cpi job from the director manifest fixes the issue.  This should not be something we do ourselves, but rather should be included as part of bosh-deployment.  Here is an example ops file that makes the change needed:

```
- type: remove
  path: /instance_groups/name=bosh/jobs/name=google_cpi
```

**Comment by cppforlife** [comment]
thats interesting given that we point director at only one cpi: https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh-lite.yml#L29

will take a look.

**Comment by cppforlife** [comment]
on second thought, what order did you specify? should be gcp/cpi.yml then bosh-lite.yml.

**Comment by ChunyiLyu** [comment]
We're specifying `gcp/cpi.yml`, then `external-ip-not-recommended.yml`, then `bosh-lite.yml`, and then our own ops file as described above to remove the unwanted google CPI job.

Removing the CPI also seems useful from the perspective of limiting potential misuse of the director; it's intended to a bosh-lite director, and any extra capabilities beyond that are just attack surface, right?

**Comment by cppforlife** [comment]
inline

Sent from my iPhone

> On Dec 29, 2016, at 3:54 PM, Chunyi Lyu <notifications@github.com> wrote:
> 
> We're specifying gcp/cpi.yml, then external-ip-not-recommended.yml, then bosh-lite.yml, and then our own ops file as described above to remove the unwanted google CPI job.
> 
interesting.
> Removing the CPI also seems useful from the perspective of limiting potential misuse of the director; it's intended to a bosh-lite director, and any extra capabilities beyond that are just attack surface, right?
> 
cpis are not exposed in any kind of way to outside except thru the director. but your point still stands (unless using multi cpi support in upcoming director).

**Comment by jaresty** [comment]
Looks like it works fine if we just deploy using those ops files in the right order.  Thanks for your help!
