### ISSUE TITLE
warden/cpi.yml causes interpolation error 

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-deployment#150]
`Could not interpolate: Expected to find exactly one matching array item for path '/releases/name=bosh-warden-cpi' but found 0`

this issues is because there is a mis configuration
https://github.com/cloudfoundry/bosh-deployment/blob/master/warden/cpi.yml#L3

this should be `path: /releases/-`
and `version:` is missing.

i will make a pull request

**Comment by cppforlife** [comment]
fixed in b848368815a2c81c59c8710850e7b56bc4649152
