### ISSUE TITLE
Update credhub.yml to v1.4.0

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/bosh-deployment#154]
Update `credhub.yml` ops file to use the latest release: http://bosh.io/releases/github.com/pivotal-cf/credhub-release?version=1.4.0

CredHub now uses `bbr-sdk-release` for backup and restore and requires this release to be co-located in order to enable bbr. (Tested with `v1.1.0`: https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/releases/tag/v1.1.0)

**Comment by cppforlife** [comment]
bumped to 1.5.0.
