### ISSUE TITLE
x509: cannot validate certificate because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by spenky** [cloudfoundry/bosh-deployment#161]
Hi,

When I run "bosh create-env", the step "Waiting for the agent on VM" fail with this message:

`
Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@X.X.X.X:6868/agent: x509: cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs
`

I use a master branch of bosh-deployment and bosh-cli v 2.0.44

Have you an idea for the solution?

Thanks.

**Comment by pivotal-jamil-shamy** [comment]
@spenky did you get this error when deploying bosh version 263 or 264 ?

**Comment by spenky** [comment]
Hi,

`commit cb8e7f60145738e103eb2dc0ad3372288986dc0c
Author: dmitriy kalinin <dkalinin@pivotal.io>
Date:   Wed Nov 8 19:30:55 2017 -0800

    bump to bosh 264.1`

**Comment by pivotal-jamil-shamy** [comment]
@spenky are you providing your own certificate for `mbus_bootstrap_ssl` ?
If not, can you check `mbus_bootstrap_ssl.certificate` certificate in the vars-store yaml file, it should have the `internal_ip` in its SAN

**Comment by cppforlife** [comment]
feel free to reopen if you did not figure it out.
