### ISSUE TITLE
Is is possible to create more than one bosh-lite on the same physical machine with bosh-deployment?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#163]
Currently I can create one bosh-lite on my local machine by the cmd below. However, I want two bosh-lite on my local machine with different names. Is is possible and how?
bosh2 create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o jumpbox-user.yml \
  -o external_ip.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork \
  -v admin_password=admin

**Comment by dpb587-pivotal** [comment]
In theory, yes. You would probably need to adjust the `internal_*` properties to ensure it's created on a separate network.

**Comment by pivotal-jamil-shamy** [comment]
@qibobo make sure to have enough resources on the physical machine to handle multi-virtual machines
