### ISSUE TITLE
update to postgres 9.5

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-deployment#164]
are there any plans to move to postgres 9.5

in bucc we use the postgresql database deployed by bosh-deployment for concourse
and in the latest concourse release they depend on pg-9.5
see https://github.com/starkandwayne/bucc/issues/49

**Comment by cppforlife** [comment]
@ramonskie there are longer term plans. not sure i understand relation to bucc, please elaborate.

**Comment by ramonskie** [comment]
bucc (bosh, uaa, credhub, concourse)
as you see bucc uses concourses.
and the latest concourse requires a pg 9.5.
as we relied on the bosh create pg database for concourse (to keep our footprint smaller)

**Comment by cppforlife** [comment]
i see, you are using bosh's postgres to host concourse db.

**Comment by jfmyers9** [comment]
We have since migrated BOSH to use postgres 10. Closing.
