### ISSUE TITLE
Show deployment tags in bosh-cli `bosh deployments`

### ISSUE THREAD

**Issue by chengwang86** [cloudfoundry/bosh-deployment#166]
Currently if I run `bosh deployments`, I can only see the `name, releases, stemcells, teams, cloud-config` in the output. Can we improve the bosh-cli so that deployment tags defined in the manifest file can also show up?

P.S., is it even possible to reference the deployment tags in the same way as other properties in the future? For example, according to here https://bosh.io/docs/jobs.html#properties, we can obtain the deployment name from `spec.deployment`; it might be useful if we can also use something like `spec.tags` to obtain the tag key value pairs.

**Comment by cppforlife** [comment]
@chengwang86 what kind of workflow are thinking about?

**Comment by chengwang86** [comment]
@cppforlife I'm thinking of having some user-defined, deployment-specific metadata as key-value pairs in the `tag` section, which can then be referenced in a release job by using `spec.tag` in the erb template of the job.

**Comment by cppforlife** [comment]
@chengwang86 any examples of what release author would use these tags for?

**Comment by donghoang89** [comment]
Being able to query bosh deployments using tag would be great.

I am managing a good number of deployments, and I would like to be able to periodically delete all the deployments which contain the tag: { "retain": false } or something a long that line.

Right now, I have to scan through the "bosh deployments" output to determine which should go.

**Comment by jfmyers9** [comment]
This issue seems more appropriate on the cloudfoundry/bosh repository. If you wish to discuss this further, please re-open the issue there.
