### ISSUE TITLE
support bosh director - not just micro-bosh

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh-deployment#171]
Bosh-deployment is really usefull to bootstrap.
However we generally do not use directly microbosh, but deploy a separate bosh director in a micro-bosh (we call it bosh-master).

In that case, we find it useful to use bosh-deployment skeleton to generate our bosh.yml manifest (without any micro-bosh specificities).

**Comment by pivotal-jamil-shamy** [comment]
@poblin-orange You can check this ops file as an example https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/bosh-dev.yml, though we use it for development only and can change at any time.

Curious to know the reasons you have the 2 BOSH's setup.

**Comment by drnic** [comment]
I've used this operator file to deploy a bosh-lite to my vsphere bosh.

**Comment by poblin-orange** [comment]
@pivotal-jamil-shamy  thks, i missed this operator. The main reason is that we want or director to benefit from health manager. Also, the systematic recompilation of the packages if micro-bosh takes too much time, whereas a bosh-master update gives reduced unavailability window

**Comment by cppforlife** [comment]
> but deploy a separate bosh director in a micro-bosh (we call it bosh-master)

we typically do not recommend doing that.

what is your use case for adding this extra layer?

**Comment by cppforlife** [comment]
> The main reason is that we want or director to benefit from health
manager. Also, the systematic recompilation of the packages if micro-bosh
takes too much time, whereas a bosh-master update gives reduced
unavailability window

ah missed your explanation.

> Also, the systematic recompilation of the packages if micro-bosh takes
too much time

with bosh-deployment, everything (except cpi) should be compiled, so should
be significantly faster to update.

> director to benefit from health manager

yeah, one of the missing features we got: connect director's agent to hm to
report its health. now perfectly covering that use case (as hm may got
dead) but sufficiently enough.

an interesting data point, we ve recently made pws only use one director
with bosh-deployment, so we ll see how our cloudops team feels about that
configuration.

**Comment by cppforlife** [comment]
closing this, as bosh-dev.yml provides this functionality. feel free to reopen if it doesnt.
