### ISSUE TITLE
Unable to install director

### ISSUE THREAD

**Issue by sumanth-suvarna** [cloudfoundry/bosh-deployment#181]
I'm trying to install director on VSphere. I'm seeing below errors and unable to proceed further.  Please help.

[CLI] 2018/01/17 17:39:25 ERROR - Deploying: Creating instance 'bosh/0': Creating VM: Creating vm with stemcell cid 'sc-5837d647-7299-492a-8600-1db93a6f49dd': CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Could not find VM for stemcell 'sc-5837d647-7299-492a-8600-1db93a6f49dd'","ok_to_retry":false}

What does the error "Could not find VM for stemcell" mean ? When does this error occur ?
I'm attaching debug log for reference.

I used below command to install director.
BOSH_LOG_LEVEL=debug BOSH_LOG_PATH=/opt/Sumanth/bosh-debug.log bosh create-env bosh-deployment/bosh.yml --state=state.json --vars-store=creds.yml -o bosh-deployment/vsphere/cpi.yml -v director_name=bosh-1 -v internal_cidr=10.234.2.0/24 -v internal_gw=10.234.2.1 -v internal_ip=10.234.2.174 -v network_name="VM Network" -v vcenter_dc="Smarts-PnS" -v vcenter_ds=wpl-vnx-002_LUN102-TEMPLATES -v vcenter_ip=10.234.24.33 -v vcenter_user='*******' -v vcenter_password='******' -v vcenter_templates=bosh-templates -v vcenter_vms=bosh-vms -v vcenter_disks=bosh-vms -v vcenter_cluster=PnS

**Comment by dpb587-pivotal** [comment]
First, please be aware that uploading the debug logs and pasting the raw CLI command you used has exposed your internal password. You should rotate your credentials, and be careful to redact information when pasting raw data in the future.

This error typically happens if you or some other automated process manually removed the stemcell/VM from vSphere without BOSH being aware, or it no longer has access to the resource. In this case, BOSH, at one point, originally created the base VM `sc-5837d647-7299-492a-8600-1db93a6f49dd` in vSphere, but it has since been removed.

To resolve this, you can edit your `state.json` file, find the `stemcells` field, and remove the entry referencing `sc-5837d647-7299-492a-8600-1db93a6f49dd`. Save the file, and try running your `bosh create-env` command again. It will re-upload the stemcell to vSphere so it can use it.

**Comment by sumanth-suvarna** [comment]
Thank you very much for your help here. I'm able to understand the reason for the error. 
Yes, you are right,. The VC center and the user i used for the first time, has no admin privileges. So, i changed the VC center and user(this time with admin rights) and executed the command again and hit the reported error.

Tried your inputs.
The issue is not resolved after removing ""cid": "sc-5837d647-7299-492a-8600-1db93a6f49dd" Seeing same error again.
Below is updated state.json file. Note that, in update state.json file, the value for "cid" is empty.

{
    "director_id": "229b46ed-7505-4dd6-71ef-72a9b21dd09f",
    "installation_id": "1ca4bf8a-4318-46b9-73b3-ea323449f335",
    "current_vm_cid": "",
    "current_stemcell_id": "",
    "current_disk_id": "",
    "current_release_ids": [],
    "current_manifest_sha": "",
    "disks": null,
    "stemcells": [
        {
            "id": "b0401eaa-5c7d-48f9-5f54-764b695da060",
            "name": "bosh-vsphere-esxi-ubuntu-trusty-go_agent",
            "version": "3468.13",
            "cid": ""
        }
    ],
    "releases": []
}

I tried again, but this time deleting entire /root/.bosh directory and re-running the command. I hit the same error again and "cid" value in state.json file is empty again. Below is the excerpt of the command line output.

Deployment manifest: '/root/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Finished (00:00:13)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Finished (00:00:17)
  Validating release 'bpm'... Finished (00:00:02)
  Downloading release 'bosh-vsphere-cpi'... Finished (00:00:05)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:48)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:01:33)

Started installing CPI
  Compiling package 'ruby-2.4-r3/8471dec5da9ecc321686b8990a5ad2cc84529254'... Finished (00:02:51)
  Compiling package 'vsphere_cpi/3049e51ead9d72268c1f6dfb5b471cbc7e2d6816'... Finished (00:01:21)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:04:14)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.13'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell ''... Failed (00:00:04)
Failed deploying (00:00:04)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid '':
        CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Could not find VM for stemcell ''","ok_to_retry":false}

Exit code 1

**Comment by cppforlife** [comment]
> Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.13'...
Skipped [Stemcell already uploaded] (00:00:00)

means that it's trying to use previous stemcell.

try removing `state.json` and running it again.

**Comment by sumanth-suvarna** [comment]
Thank you for all your support.
I could install director successfully since i'm able to understand the error now. I deleted /root/.bosh and /root/bosh-1 directory, started from scratch. It worked. Since i didn't knew when state.json file will be created, i have to start again from scratch. 

My main intention is to create a new bosh release with a binary installer(lets say, a setup.bin file) to install our product on a VM using bosh. The whole idea is to use Bosh and concourse combo for test automation. May i know how to go about it Or where can i post this question so that i get some pointers.

**Comment by dpb587-pivotal** [comment]
The `state.json` file is created when running `create-env` and retains the references to IaaS resources used so they can be updated and cleaned up later. I'm glad you were able to deploy director.

Sounds like you are also looking to experiment with [Concourse](https://concourse.ci)? If so, I think you'd be interested in [concourse/concourse-deployment](https://github.com/concourse/concourse-deployment/tree/master/lite) where there's an option to bring a Concourse instance up for testing in a very similar manner to what you accomplished here.

**Comment by sumanth-suvarna** [comment]
I have deployed Concourse using Bosh, but the main challenge for me is to install my software on a VM using bosh. I know i have to create a bosh release with my software. I will explain the entire process that needs to be automated to install my software.

1. Let's say, my software can be installed silently on a CentOS machine. To do this, i have to run ./setup.bin -i <silent file> on a VM.  I understand i have to create a bosh release where-in i create a tar file for setup.bin and silent file and place it in src directory.  In the packaging spec, i have to provide the name of tar file under "files: []".  I also created a packaging script with below contents.

set -e -x
tar zxf IPInstaller.tar.gz
cp -a IPInstaller ${BOSH_INSTALL_TARGET}
${BOSH_INSTALL_TARGET}/IPInstaller/setup-IP-9_4_2_0-linux64.bin -options ${BOSH_INSTALL_TARGET}/IPInstaller/IP_NETWORK_SUITE-response.txt

Here, IPInstaller.tar.gz is the name of the tar file. Last line represents the command to install my software where "setup-IP-9_4_2_0-linux64.bin" is the installer and "IP_NETWORK_SUITE-response.txt
" is the silent properties file.

**I'm not sure whether this is the right way to do it. If not, please do let me know.**

Given this, i know the install will fail on fresh CentOS OS installed using stemcell. It's because, to install my software, following libraries has to be installed on CentOS before installing my software. 
• glibc-2.2.4-32.i686
• glibc-2.2.4-32.x86_64
• glibc-common-2.2.4-32
• compat-libstdc++-33-3.2.3-61.x86_64
• compat-libstdc++-33-3.2.3-47.3.i686
• redhat-lsb-4.1-24.x86_64

Now, my questions is 
1. How do i create a release to install my software along with above dependent libraries ? How do i know and resolve if above mentioned libraries has dependency on other libraries ? 

2. I know i can use yum command to install above libraries which will install all dependent libs automatically, but how do i do it using bosh release ?

Thank You.

**Comment by sumanth-suvarna** [comment]
Also, Is there any way to make bosh agent install rpm file before installing my software ? Your suggestions and inputs will help me a lot.

**Comment by sumanth-suvarna** [comment]
Thank you for the response, but i'm still not very clear on how to go about it. I have below followup questions to get clear understanding.. The software i want to install has no compile time dependency since i will be running executable installer which is already compiled and built.(Ex : ./setup.bin) It's just that, my software installation needs 6 binaries(which i already mentioned above and it has no strict version dependency; latest version will also work) that has to be already installed in the system before installing in my software.

1. When you said that the packages(required libs/rpms) should be pre-installed on the CentOS image, are you telling that i should generate a new stemcell from a CentOS image which has all required libs installed and use that newly generated stemcell for deployment ?

2. Yes, i'm working on a enterprise environment which has no access to yum repositories, but maintains local yum repositories. When you said that rpms should be installed through packaging, are you telling that i create a package for all dependent rpms and install them using "configure, make and make install" commands ? 

Thank you for your help.
