### ISSUE TITLE
Unable to change vcap user password with env.bosh.password

### ISSUE THREAD

**Issue by sumanth-suvarna** [cloudfoundry/bosh-deployment#187]
Hello,

I'm trying to change the default password(which is unknown) of vcap user by specifying sha-512 hashed password as value to "env.bosh.password" in my cloud config yml file. It did not work. The VM was deployed successfully but i wasn't able to login using vcap user.  From the add-on user, i opened the /etc/shadow file and could see that password is not set for user vcap. See below.
                      "vcap:*:17563:1:99999:7:::"

Below is the content of my test cloud config and manifest file. Please let me know what i'm doing wrong here. This is something very important for my project.

My test Cloud Config file..
azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: Smarts-PnS
      clusters: [PnS: {}]

vm_types:
- name: small
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 10_000
  env:
    bosh:
      password: '$6$AJzVBybf$B2mUzv98rSGtHNGZgpAtL0IkJ8M.NspzWMqo9Rz76MNukYPNXpxCGbJwHQByG59fIi7RHRTmIne.mhdWimRO.0'

- name: medium
  cloud_properties:
    cpu: 2
    ram: 6144
    disk: 20_000
  env:
    bosh:
      password: '$6$AJzVBybf$B2mUzv98rSGtHNGZgpAtL0IkJ8M.NspzWMqo9Rz76MNukYPNXpxCGbJwHQByG59fIi7RHRTmIne.mhdWimRO.0'

- name: large
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 30_000
  env:
    bosh:
      password: '$6$AJzVBybf$B2mUzv98rSGtHNGZgpAtL0IkJ8M.NspzWMqo9Rz76MNukYPNXpxCGbJwHQByG59fIi7RHRTmIne.mhdWimRO.0'

- name: x-large
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 40_000
  env:
    bosh:
      password: '$6$AJzVBybf$B2mUzv98rSGtHNGZgpAtL0IkJ8M.NspzWMqo9Rz76MNukYPNXpxCGbJwHQByG59fIi7RHRTmIne.mhdWimRO.0' 

disk_types:
- name: small
  disk_size: 10_000
- name: medium
  disk_size: 20_000
- name: large
  disk_size: 30_000
- name: x-large
  disk_size: 40_000

networks:
- name: Admin
  type: manual
  subnets:
  - range: 10.234.2.0/24
    gateway: 10.234.2.1
    az: z1
    dns: [10.106.16.22,10.106.16.23]
    cloud_properties: {name: "VM Network"}
    static: [10.234.2.175,10.234.2.176,10.234.2.181]
    reserved: []
- name: Compile
  type: manual
  subnets:
  - range: 10.234.2.0/24
    gateway: 10.234.2.1
    az: z1
    dns: [10.106.16.22,10.106.16.23]
    cloud_properties: {name: "VM Network"}
    reserved: [10.234.2.1-10.234.2.179,10.234.2.181-10.234.2.254]

compilation:
  workers: 1 
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: Compile
---------------------------------------------------------------------------------------------------

My manifest file 

name: sumanth
director_uuid: 9a65f44a-22e9-4eae-ad8d-6d26ef4f375e
releases:
- name: os-conf
  version: latest
stemcells:
- alias: centos
  os: centos-7
  version: 3468.21
update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: os-configuration
  instances: 1
  networks:
  - name: Admin
    static_ips: [10.234.2.181]
  jobs:
    - name: login_banner
      release: os-conf
      properties:
        login_banner:
          text: |
            Authorized Use Only.
            Unauthorized use will be prosecuted to the fullest extent of the law.
    - name: user_add
      release: os-conf
      properties:
        users:
        - name: bossuser
          shell: /bin/bash
          crypted_password: $6$vvvvvvvv$iV58R0uY51Ka8yspJIqOaCFCj/Ccm6Sx.ajyFsrVN829gm/zBfRF7UGaB5eWQyYEUOSysxs/HcA2hDId4sog01
  azs: [z1]
  stemcell: centos
  vm_type: x-large
  persistent_disk_type: x-large
----------------------------------------------------------------------------------------------------

Let me know if you want any further information from my end.

Regards...

**Comment by cppforlife** [comment]
note that env configuration goes on an instance group, not on vm type.

http://bosh.io/docs/manifest-v2#instance-groups

**Comment by sumanth-suvarna** [comment]
Thank You so much @cppforlife . I'm able to login as vcap user now, but not as root user using ssh.

I included env configuration in cloud config file under vm type after following instructions in 
http://www.starkandwayne.com/blog/hardening-the-vcap-users-password-on-bosh-vms/

I checked /etc/shadow file for root user and vcap user and it looks fine and hashed password is updated.
What's actually happening is "The root user is denied ssh login in /etc/ssh/sshd_config file".

Below entry in /etc/ssh/sshd_config file clears that root user is denied ssh login permission.
PermitRootLogin no
DenyUsers root

So, my question is; is there any way, during deployment to comment out above 2 lines and add below line to /etc/ssh/sshd_config file.
PermitRootLogin yes

Please let me know as i'm looking to login to bosh deployed VMs using root instead of vcap.

Thank You,
Sumanth Suvarna.

**Comment by dpb587-pivotal** [comment]
No, root user is intentionally denied access per standard security recommendations.

However, since you now have access to the `vcap` user, you can use `sudo` to gain root access.

More specifically though, we don't recommend static logins across your BOSH-deployed VMs. Typically you should be using `bosh ssh` to gain access to VMs for manual/one-off interactions. The `bosh ssh` command creates ephemeral user accounts on VMs and provides better audit abilities within BOSH.

**Comment by sumanth-suvarna** [comment]
Understood. Thank You.
