### ISSUE TITLE
Virtual disks are not deleted when deployment is deleted using bosh

### ISSUE THREAD

**Issue by sumanth-suvarna** [cloudfoundry/bosh-deployment#189]
At present, I'm not sure whether this is an issue or i'm missing something; Virtual disks are getting created as part of bosh director and deployments but are not getting deleted when bosh deployment and bosh director are deleted. 

I used below command to create director.
bosh create-env bosh-deployment/bosh.yml -o bosh-deployment/misc/dns.yml -v internal_dns=[10.106.16.22,10.106.16.23] --state=state.json --vars-store=creds.yml -o bosh-deployment/vsphere/cpi.yml  -v director_name=bosh-1 -v internal_cidr=10.234.2.0/24 -v internal_gw=10.234.2.1 -v internal_ip=10.234.2.174 -v network_name="VM Network" -v vcenter_dc="Smarts-PnS" -v vcenter_ds=wpl-vnx-002_LUN101-TEMPLATES -v vcenter_ip=10.234.24.33 -v vcenter_user='some user' -v vcenter_password='some password' -v vcenter_templates=bosh-templates -v vcenter_vms=bosh-vms -v vcenter_disks=bosh-disks -v vcenter_cluster=PnS

Director is installed and i see a new directory "bosh-disks" is created in datastore as expected and i'm seeing virtual disks in it. But when i delete the director, these virtual disks are not getting deleted.

I used below command to delete the director.
bosh delete-env bosh-deployment/bosh.yml -o bosh-deployment/misc/dns.yml -v internal_dns=[10.106.16.22,10.106.16.23] --state=state.json --vars-store=creds.yml -o bosh-deployment/vsphere/cpi.yml  -v director_name=bosh-1 -v internal_cidr=10.234.2.0/24 -v internal_gw=10.234.2.1 -v internal_ip=10.234.2.174 -v network_name="VM Network" -v vcenter_dc="Smarts-PnS" -v vcenter_ds=wpl-vnx-002_LUN101-TEMPLATES -v vcenter_ip=10.234.24.33 -v vcenter_user='*******' -v vcenter_password='*******' -v vcenter_templates=bosh-templates -v vcenter_vms=bosh-vms -v vcenter_disks=bosh-disks -v vcenter_cluster=PnS

The same behavior is seen for any other bosh deployments.

Impact
Our automation, which is based on concourse-bosh model, creates VM, runs tests and deletes VM at the end. Over a period of time, the datastore runs out of space since the virtual disks are not getting deleted. 

Let me know if i'm missing anything here or is it an issue or is it an expected behavior.

Regards,
Sumanth Suvarna.

**Comment by cppforlife** [comment]
see info here about persistent disks: http://bosh.io/docs/persistent-disks#orphaned-disks. this is a safety feature against accidental data loss.

before running delete-env command we also expect for operator to delete deployments and then run ‘bosh clean-up —all’ before deleting the director to reclaim all resources.

**Comment by sumanth-suvarna** [comment]
Great. Thank you. I can now delete orphaned disks by running 'bosh clean-up --all' command.

In the link," https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=director.disks "
 i came across a property 'max_orphaned_age_in_days: 5', may i know how to set it to 1 and where do i set it.

**Comment by cppforlife** [comment]
@sumanth-suvarna you can set it by using an ops file below when running create-env:

```
- type: replace
  path: /instance_groups/name=bosh/properties/director/disks?/max_orphaned_age_in_days
  value: 1
```

**Comment by sumanth-suvarna** [comment]
Thank you so much for the response.
I have created a new ops file with above contents and executed create-env command with --ops-file option. Command got executed successfully. How do i ensure/cross-check that max_orphaned_age_in_days is set to 1. Is there any file which i can check ? Please let me know.

Regards,
Sumanth Suvarna.

**Comment by sumanth-suvarna** [comment]
Thank you very much... 👍
