### ISSUE TITLE
BOSH with external IP sets too many options for us

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh-deployment#191]
Hi all

When we deploy a new CF platform to an empty (VCenter) tenant, we have to deploy BOSH first.

We achieve this by deploying it from the outside - BOSH's IP is exposed to a mgmt network using a LB. Once BOSH is deployed, we create our deployments on this BOSH. These deployments also include a bastion VM where we do the management from this point on.

For this, we use `external-ip-not-recommended.yml`. 
I guess this ops file was created with a very specific scenario in mind (probably AWS with external IPs). We'd like to use this ops file for our scenario.

However, we only need the [following operations regarding mbus](https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml#L24-L34):
```
- type: replace
  path: /cloud_provider/mbus
  value: https://mbus:((mbus_bootstrap_password))@((external_ip)):6868

- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options/alternative_names/-
  value: ((external_ip))

- type: replace
  path: /variables/name=director_ssl/options/alternative_names/-
  value: ((external_ip))
```

We don't need the other operations:
- [Equipping the BOSH director with a public interface](https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml#L3-L17) with this IP is not needed since the LB has the IP and speaks to BOSH with a private IP
- [Setting the external IP as default ssh gateway](https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml#L19-L21)  is not needed, since most BOSH interactions take place from the Bastion VM which can talk to BOSHs private interface directly

How could we fit our use case in your ops files? It's probably a philosophic matter of how you want to compose ops files...

- Shall I create a seperate ops file for our use case, i.e. `external-ip-mbus-only`, causing some redundancies in the two ops files
- Break up the external ip files in more modular parts
- Other options...?

**Comment by cppforlife** [comment]
@MatthiasWinzeler how are you attaching your LB to the director vm?

**Comment by MatthiasWinzeler** [comment]
@cppforlife I'm not sure I understand your question fully; the LB (hardware, maintained by a 3rd party team) is preprovisioned beforehand and has the director VM IP as its pool members (which it can reach with a L3 connection). The member will first be down and become available as soon as the director VM gets available.

**Comment by cppforlife** [comment]
> VM IP as its pool members

i see, i was wondering if an LB was automatically attached via some API call or something like that. sounds like it is just preconfigured. 

i think we can add this as a separate ops file, though we should probably put it under `misc/external` directory to make it a bit more organized.

**Comment by MatthiasWinzeler** [comment]
@cppforlife cool; created PR #198 for it. feel free to reorganize as you see fit.
