### ISSUE TITLE
Concourse installation using Bosh CLI fails with error

### ISSUE THREAD

**Issue by sumanth-suvarna** [cloudfoundry/bosh-deployment#199]
I'm trying to install concourse lite using bosh cli on Cent OS VM by following the steps in link https://concourse.ci/concourse-lite.html

I'm getting below error during install process. I'm unable to figure out why the error is occurring and what does it mean. Please do help me out here.

bosh -e bosh-1 create-env manifests/concourse-lite.yml --state tmp/state.json
Deployment manifest: '/opt/Sumanth/ConcourseTutorials/manifests/concourse-lite.yml'
Deployment state: 'tmp/state.json'

Started validating
  Downloading release 'concourse'... Skipped [Found in local cache] (00:00:00)
  Validating release 'concourse'... Finished (00:00:04)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:01)
  Downloading release 'postgres'... Skipped [Found in local cache] (00:00:00)
  Validating release 'postgres'... Finished (00:00:02)
  Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:03)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:04)
Finished validating (00:00:16)

Started installing CPI
  Compiling package 'golang-1.8-linux/c97f9a00c26b34a3f59ca15b0f5a079d7f7e27c334cc8100248143c5dc0d4c0a'... Finished (00:00:25)
  Compiling package 'golang-1.8-darwin/ee2bb46a25872469cd8fe0f4b0804bab5c39cc5512bbcc4335c8691a038d3e73'... Finished (00:00:25)
  Compiling package 'virtualbox_cpi/cb3116b9b6c2111a873bb4ea14a1f3544ccdd2af'... Finished (00:00:23)
  Installing packages... Finished (00:00:08)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:01:23)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.11'... Failed (00:02:09)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3468.11):
  **CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Importing stemcell from '/root/.bosh/installations/a511484e-14b6-4491-4c9a-37beea0d3422/tmp/stemcell-manager063439831/image': Retried '2' times: Retried '30' times: Starting command 'VBoxManage import /root/.bosh_virtualbox_cpi/stemcells/sc-2dde56da-373c-464d-6fd2-19946a20bf08/image.ovf': exec: \"VBoxManage\": executable file not found in $PATH","ok_to_retry":false}

Exit code 1**

Post unsuccessful installation, i found that the directory "/root/.bosh/installations/a511484e-14b6-4491-4c9a-37beea0d3422/tmp" is empty and so, the stemcell "/root/.bosh/installations/a511484e-14b6-4491-4c9a-37beea0d3422/tmp/stemcell-manager063439831/image" doesn't exists at all.

**Comment by sumanth-suvarna** [comment]
I'm facing this issue consistently even after deleting and creating bosh director. I'm using VMWare VSphere as cloud provider. I'm unable to install concourse using bosh because of same error again and again. Not sure how to proceed.

creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3468.11):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Importing stemcell from '/root/.bosh/installations/c2f8b12d-eb0d-47ca-70d5-e14574078adb/tmp/stemcell-manager418778541/image': Retried '2' times: Retried '30' times: Starting command 'VBoxManage import /root/.bosh_virtualbox_cpi/stemcells/sc-ef712e2b-5040-471b-4d59-0885427b1311/image.ovf': exec: \"VBoxManage\": executable file not found in $PATH","ok_to_retry":false}

Exit code 1

**Comment by ghantk1** [comment]
for the lite version, the cpi should be vboxManage, basically, you are trying to build the cluster on VBOX MANAGER. you should use vbox as cpi, here is an example https://github.com/concourse/concourse-deployment/tree/master/cluster/cloud_configs

**Comment by dpb587-pivotal** [comment]
As mentioned, it looks like your `manifests/concourse-lite.yml` wants to deploy to a local VirtualBox environment which you do not appear to have installed. I'd recommend taking a look at the official [concourse/concourse-deployment](https://github.com/concourse/concourse-deployment/tree/master/lite) repository for more details and the manifests they maintain.

**Comment by sumanth-suvarna** [comment]
Yes, i don't have local virtual box environment. Thank you for clarification.
