### ISSUE TITLE
default to v3 or v2 openstack?

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-deployment#2]
@voelzmo 

Currently `openstack/cpi.yml` defaults to v2 config options and there is `openstack/keystone-v3.yml` to use v3. Should we default to v3 and have v2 override?

**Comment by voelzmo** [comment]
Yup, definitely. I switched the template on http://bosh.io/docs/init-openstack.html to v3 some weeks ago and provided information on how to switch on v2 with http://bosh.io/docs/openstack-keystonev2.html
