### ISSUE TITLE
ipv6 change broke ipv4+ipv6 test-stemcells

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-deployment#205]
revert: https://github.com/cloudfoundry/bosh-deployment/commit/96d644bc54f6ab074fab1b1a2d7801113742cb6e

https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:stemcells/jobs/test-stemcells/builds/224

cc @cunnie

**Comment by dpb587-pivotal** [comment]
Closing - seems like it is no longer broken and not sure what else may be necessary. If more changes need to happen, feel free to test them out and PR them separately.
