### ISSUE TITLE
Bosh director failed to deploy 

### ISSUE THREAD

**Issue by Velann** [cloudfoundry/bosh-deployment#212]
We have few bosh directors deployed already in a vcenter, But when we tried to deploy another one with the new vcenter details. I am getting the below error which i havent faced before.

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-d4044208-5393-4327-88fc-90601cc05395':
        CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Could not transfer file 'https://10.234.2.182/folder/vm-94b9601d-c091-4260-97e2-1525c6fcaf08/env.json?dcPath=White%!P(MISSING)lains\u0026dsName=wpl-vnx002_LUN45', received status code '401'","ok_to_retry":false}

Exit code 1

**Comment by amuessig** [comment]
You should provider more details. How do you deploy (`bosh create-env` or `bosh deploy`)?
Furthermore, you could enable `http_logging` to get further debugging output

**Comment by dpb587-pivotal** [comment]
You may want to double check the value you are using for the datacenter name in your manifest - it looks incorrect in the URL you pasted (`White%!P(MISSING)lains`).

In general, the 401 error refers to incorrect authorization or authentication information.

If you need more logging, you may want to check these global [logging options](http://bosh.io/docs/cli-global-flags#logging). Be careful of removing sensitive information if posting more logs.

**Comment by dpb587-pivotal** [comment]
Closing - the latest question was created as #216.
