### ISSUE TITLE
Bump warden cpi to v39

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-deployment#214]
Related to https://github.com/starkandwayne/bucc/issues/92

I'm looking to use `vm_resources`, but its failing. Perhaps because `warden/cpi.yml` includes warden-cpi v35, but latest is v39. Sadly, bosh-warden-cpi-release doesn't have github releases for all releases; last was v37 which looks to predate https://github.com/cppforlife/bosh-warden-cpi-release/commit/6bfcac5c2b50d7dc24c3bc45d7e2b81ec1406a8f

Nothing in https://github.com/cppforlife/bosh-warden-cpi-release/releases notes suggests if/when https://bosh.io/docs/cpi-api-v1.html#calculate-vm-cloud-properties is implemented.

**Comment by ramonskie** [comment]
it seems that it was implemented in v38
see commit https://github.com/cppforlife/bosh-warden-cpi-release/commit/6bfcac5c2b50d7dc24c3bc45d7e2b81ec1406a8f

**Comment by cppforlife** [comment]
latest set of commits bumps bunch of stuff.
