### ISSUE TITLE
connections hang while communicating to other instances on bosh-lite

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-deployment#215]
We're seeing issues while trying to communicate with other instances on bosh-lite. 

For instance, the following `curl` command should return immediately with a 404
```
# time curl -k https://blah.1520867754.bosh-lite.gcp.core-services.cf-app.com/
404 Not Found: Requested route ('blah.1520867754.bosh-lite.gcp.core-services.cf-app.com') does not exist.

real	0m0.079s
user	0m0.008s
sys	0m0.000s
```

But we're seeing very long hangs for some requests
```
# time curl -k https://blah.1520867754.bosh-lite.gcp.core-services.cf-app.com/
404 Not Found: Requested route ('blah.1520867754.bosh-lite.gcp.core-services.cf-app.com') does not exist.

real	1m44.501s
user	0m0.008s
sys	0m0.004s
```

Those curl commands are being executed on containers which have been deployed by the bosh-lite.

We eventually lowered the mtu size on our `gorouter` container instance from `1460` to `1400` and that appears to fix the issue. We no longer see the issue when we lower the mtu size on the container.

We first started seeing this issue with the following git shas: 
bosh-deployment: 5365bcb9116895ec8b52f325313dc22740237223
cf-deployment: 20e949909c1136753f4b43e532c04c3cf02f64ac
stemcell: 3541.4

We are still seeing this issue with the latest versions of all deployments and stemcells.

We've deployed our bosh-lites on GCP with the following opsfiles:
```
gcp/cpi.yml
bosh-lite.yml
bosh-lite-runc.yml
bosh-lite-grootfs.yml
external-ip-not-recommended.yml
jumpbox-user.yml
uaa.yml
external-ip-not-recommended-uaa.yml
credhub.yml
```

This is rendering some of our bosh-lites unusable. We do not always see this when we provision a bosh-lite, but when we do, it never goes away.

We can provide deployments for you to look at so that we can work together to debug this issue.

Do you all have any idea why this would be happening?

cc @jpalermo

**Comment by dpb587-pivotal** [comment]
Note to self, a bit more discussion about investigating this is in [private slack](https://pivotal.slack.com/archives/C5JQWSVJ6/p1520635020000015).

**Comment by zankich** [comment]
Closing for now, we'll reopen this issue if it pops up again. Thanks!

**Comment by dpb587-pivotal** [comment]
Very strange - thanks for following up.
