### ISSUE TITLE
Is the domain "bosh-lite.com" persisted in bosh-lite vm?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#224]
I create a bosh-lite vm with the domain *.bosh-lite.com and it works. Then I created another bosh-lite vm and deploy cf on it with domain "*.bosh-lite2.com", but the domain can not be accessed. For example:
ping api.bosh-lite2.com failed.
curl https://api.bosh-lite2.com/v2/info failed.

**Comment by mkuratczyk** [comment]
Hi. I'm not sure I understand the question but bosh-lite.com is a real domain registered on the internet, although it returns a private (RFC1918) address:
$ host api.bosh-lite.com 8.8.8.8
api.bosh-lite.com has address 10.244.0.34

$ host api.bosh-lite2.com 8.8.8.8
Host api.bosh-lite2.com not found: 3(NXDOMAIN)

You'd need to add *.bosh-lite2.com to your local DNS server for this to work.

**Comment by dpb587-pivotal** [comment]
As mentioned by @mkuratczyk, your initial deployment is probably taking advantage of the pre-registered example domain which happens to be using the correct IP to work. You probably want to add an entry for bosh-lite2 in your local environment.

To answer your question though, the system domain of CF is not explicitly hard-coded to your system or bosh-lite VMs. It relies on existing DNS lookups for resolution. Internal communication is handled automatically and does not generally use the system domain.
