### ISSUE TITLE
Could you create stable release for bosh deployment?

### ISSUE THREAD

**Issue by yukikashiwabara** [cloudfoundry/bosh-deployment#228]
Are there any stable version to deploy the same bosh environment whenever we try to deploy?

**Comment by ramonskie** [comment]
it would be nice to have some versioning in place.
there has been plenty of times when a commit broke the deployment.

**Comment by cppforlife** [comment]
@ramonskie i would be curious to hear your thoughts on what changes you would consider as breaking.

**Comment by ramonskie** [comment]
If my memory serves me well,
When bosh changed to nats+tls we had some breaking changes.
and this was due that we needed tot create our creds.yml again.
and when switching from credhub user to credhub client.

**Comment by cppforlife** [comment]
@ramonskie interesting.

> When bosh changed to nats+tls we had some breaking changes.

hmm, im surprised that this ended up breaking your env. it was meant to be transparent as certs get generated automatically via --vars-store flag.

> and when switching from credhub user to credhub client.

we didnt realize that this would break users.

do you think marking off each change as major would still be beneficial? for a lot of these changes it almost always may affect someone depending on how they are using the system.

**Comment by ramonskie** [comment]
@cppforlife well to be honest we use bosh-deployment and the way you can use bosh pretty extensively.
so maby its only something we run into.

and to be honest. if  i look at the commit history from the last year. and only these 2 issues we had.
i would say its pretty stable :+1:

**Comment by aeijdenberg** [comment]
As feedback the bump to 266.2 and related changes earlier this week caused 3 different issues for our CloudFoundry deployment to AWS:

- CloudFoundry using external database operator file broke: https://github.com/cloudfoundry/cf-deployment/pull/525
- Bosh using AWS S3 for blob storage broke: https://github.com/cloudfoundry/bosh-deployment/issues/254

And lastly, though possibly less likely bosh's fault, except perhaps for the hard to decipher error message:

- Docker-Broker release "external IP" issue: https://github.com/cloudfoundry/bosh/issues/1639

We sure would appreciate using the GitHub releases. `cf-deployment` does this really well - and for example it's easy to setup an integration to dump new GitHub release notes into a Slack channel, which is great for picking up any notes that operators need to read.

**Comment by cppforlife** [comment]
i've created v1.0.0, and will be adding versions in future; however, do note that we currently don't offer lts versions for bosh-deployment. cc @luan
