### ISSUE TITLE
UAA + Credhub ops-files become default

### ISSUE THREAD

**Issue by genevieve** [cloudfoundry/bosh-deployment#231]
Will the features of the `credhub.yml` and `uaa.yml` ops-files become default in `bosh-deployment.yml`? Would you accept a PR that enabled these features by default (now that they are stable and no longer experimental) and created ops-files that disable these two releases?

**Comment by cppforlife** [comment]
@genevieve i've been thinking about it as well, though i do like current separation and pluggability. as of now, im planning to keep them as it is. (they are also not experimental since they leave at the root).

**Comment by evanfarrar** [comment]
We've got dozens of teams testing this with uaa+credhub enabled though, and fewer running recent versions of bosh-deployment with them disabled, so we should call out *not* enabling these as more outside the norm and slightly less likely to work. With two ops files that disable uaa and credhub individually, operators would have the same configurability (and the same frustration around not understanding which features depend on which, but at least fewer people would have to experience that).

**Comment by ramonskie** [comment]
i would recommand to hold it off until they fixed 
https://github.com/cloudfoundry-incubator/credhub/issues/33

**Comment by evanfarrar** [comment]
I still think it should be the default, we have not observed the issue described with Credhub.

**Comment by voelzmo** [comment]
The issue with growing DB has been fixed in CredHub with 1.9.2 when they moved to writing audit-relevant data to a logfile instead of the DB. If that was the only reason keeping us from using UAA and CredHub as a default, then go for it.

**Comment by mfine30** [comment]
Hey @evanfarrar, I know Genevieve isn't on your team anymore. Is the infrastructure team still interested in submitting a PR for this issue? We'd be interested in receiving one.

**Comment by genevieve** [comment]
😢
