### ISSUE TITLE
Include create-env secrets in credhub

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/bosh-deployment#232]
Hi, we had some trouble in the past maintaining our secrets files for the bosh directors. Most of the time we keep them on our jumphost and in 1Password. But its hard to keep the secrets up to date in the 1Pass and not to lose it on the jumphost by an accidental `rm`.

What do you think about a feature in bosh-deployment that checks after create-env is finished if a credhub is deployed with the director and then imports all the director secrets there?

Think about it, after i made a bosh create-env, i only have to remember my credhub credentials. This will also give me an easy solution for updating the bosh director with Concourse since the credentials are available from within the director.

We are facing the same problem with bosh state file. For me it would be great if we could either move it into credhub as well, or if the director is able to generate it with an cli command.

best,
Dennis

**Comment by drnic** [comment]
Have a look at https://github.com/cloudfoundry/bosh-cli/pull/407 as one possible path forward.

I don't think you want the credentials for your BOSH stored inside the same BOSH VM. If anything goes wrong with your BOSH VM you can't get the credentials back out to redeploy it?

One idea I've had is to resurrect the Binary BOSH idea [1] for BOSH/UAA/Credhub - where your BOSH is deployed by a 2nd "meta" BOSH, and in return the meta BOSH is deployed by the primary BOSH. The secrets for each BOSH is held in the alternate BOSH's credhub.



[1] https://starkandwayne.com/blog/resurrecting-bosh-with-binary-boshes/
