### ISSUE TITLE
bosh lite resume error

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#236]
I create a bosh lite use bosh create-env, then I used "vboxmanage controlvm xxx savestate" to stop the vm, then "vboxmanage startvm xxx -type headless". After all steps, the vm status is running, but I can not access the bosh director. I can ping 192.168.50.6 but can not bosh.
Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: dial tcp 192.168.50.6:25555: getsockopt: connection refused

**Comment by cppforlife** [comment]
currently unfortunately bosh vsphere stemcell (used with vbox cpi) does not properly remount persistent disk in vbox environment (opened here: https://github.com/cppforlife/bosh-virtualbox-cpi-release/issues/7). i would recommend to pause/resume for now instead of savestate/startvm.
