### ISSUE TITLE
Use 1.1.1.1 instead of 8.8.8.8

### ISSUE THREAD

**Issue by PG2000** [cloudfoundry/bosh-deployment#239]
Maybe it can be an improvement to use 1.1.1.1 as default dns.

The advantages are:
Privacy is Guaranteed.
It seems faster than 8.8.8.8

**Comment by cppforlife** [comment]
@PG2000 i think it was found in the wild that in some cases 1.0.0.1 and 1.1.1.1 could be blocked.
