### ISSUE TITLE
Please provide instructions for configuring network 

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-deployment#24]
In the instructions 
"Note: Above assumes that you have configured Host-only network 'vboxnet0' with 192.168.50.0/24 and NAT network 'NatNetwork' with DHCP enabled."

@cppforlife showed me this config has to be done in the Virtualbox UI. I would not have known what to do otherwise, and without this step it took 7min to contact the agent. 

Please replace this text with step by step instructions.

Thank you!

**Comment by cppforlife** [comment]
doc page updated with links.
