### ISSUE TITLE
bump uaa to 57.1> will fix os-conf collocate error

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-deployment#247]
when uaa and os-conf are co-located. the pres-start script of the uaa will fail see

https://github.com/cloudfoundry/uaa-release/issues/72
https://www.pivotaltracker.com/story/show/156412250

see also the release notes of uaa 57

**Comment by ramonskie** [comment]
bump to 59 othwerwise it will also result in the following error https://www.pivotaltracker.com/n/projects/997278/stories/157267831

**Comment by cppforlife** [comment]
bumped.
