### ISSUE TITLE
Upgrade to credhub 1.9.2

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-deployment#252]
Can we please upgrade credhub-release to 1.9.1+ so we remove the ever-growing audit log table from the DB? Originally raised in https://github.com/cloudfoundry-incubator/credhub/issues/33 and looks to be fixed in 1.9.1 + 1.9.2 https://github.com/pivotal-cf/credhub-release/releases/tag/1.9.1

Updating credhub-release in bosh-deployment is a dependency for https://github.com/starkandwayne/bucc/issues/129

**Comment by cppforlife** [comment]
@drnic in progress of bumping things...

**Comment by cppforlife** [comment]
bumped in latest
