### ISSUE TITLE
Bosh v266.2.0 is broken

### ISSUE THREAD

**Issue by katter** [cloudfoundry/bosh-deployment#259]
Hi, v266.2.0 of bosh is broken. Since it's referenced in master of bosh-deployment, bosh-deployment deployed directors will for instance be unable to deploy cf-deployment:
https://github.com/cloudfoundry/bosh/issues/1975

This is fixed in v266.3.0 so it would be nice to have that updated in bosh.yml

As well, would it be possible to tag bosh-deployment alongside with bosh so we don't have to checkout commits?

**Comment by cppforlife** [comment]
@katter updated to 266.4.0
