### ISSUE TITLE
External DNS variable on bosh.yml

### ISSUE THREAD

**Issue by andrearagao** [cloudfoundry/bosh-deployment#263]
On this page https://docs-cfcr.cfapps.io/installing/vsphere/deploying-bosh-vsphere/ you have this instruction to update ~/kubo-deployment/bosh-deployment/bosh.yml and replace 8.8.8.8 with an internal DNS name when necessary. Why don't you make this variable externalized as the rest of the network variables? I suggest using dns_recursor_ip as that is a variable that is already available in director.yml:

`networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static: [((internal_ip))]
    dns: [((dns_recursor_ip))]`

**Comment by mrosecrance** [comment]
Closing as it seems like there's no longer a recommendation to change the dns that I can find.
