### ISSUE TITLE
Unable to deploy bosh director in vCloud Director 9.1

### ISSUE THREAD

**Issue by Krishnakantsingh16** [cloudfoundry/bosh-deployment#266]
Hi All,

I am getting the following error while testing new bosh director in vCloud Director 9.1

Looking for an advise to fix this issue.

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'urn:vcloud:catalogitem:cfba03ad-2b1d-484d-8503-3390068bd417'... Failed (00:02:00)
Failed deploying (00:02:00)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'urn:vcloud:catalogitem:cfba03ad-2b1d-484d-8503-3390068bd417':
        CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"400 Bad Request","ok_to_retry":false}

Exit code 1

Cli version 3.0.1-712bfd7-2018-03-13T23:26:43Z
bosh release version: "266.2.0"
Stemcell:bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.16
vCloud Director 9.1

Debug log:

 HTTP 400 Bad Request&#xA; - cvc-complex-type.2.4.a: Invalid content was found starting with element 'rasd:InstanceID'. One of '{&quot;

**Comment by h4xnoodle** [comment]
Hi @Krishnakantsingh16 apologies for the delay in responding.

Does this issue still happen for you? If so, please reopen.
