### ISSUE TITLE
s3 blobstore question

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry/bosh-deployment#267]
With v1.1.0, it seems to require "blobstore.tls.cert.private_key" although we use S3 blobstore. would you check? 

Running command: 'ruby /root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/erb-renderer855283525/erb-render.rb /root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/erb-renderer855283525/erb-context.json /root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/bosh-release-job094525505/templates/server_tls_private_key.pem.erb /root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/rendered-jobs518268926/config/server_tls_private_key.pem', stdout: '', stderr: '/root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/erb-renderer855283525/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/c0c032cf-e092-4b45-4673-c0a96eca6d6a/tmp/bosh-release-job094525505/templates/server_tls_private_key.pem.erb' for blobstore/0 (line 1: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'blobstore.tls.cert.private_key'>) (RuntimeError)

**Comment by aeijdenberg** [comment]
@marcus-sds - in case it's helpful, we also recently had issues with S3 for blobstore. We were able to fix as documented in https://github.com/cloudfoundry/bosh-deployment/issues/254.

**Comment by marcus-sds** [comment]
I think it's issue with tls cert property is still required although we use
s3 opsfiles. If it's expected result,we can set property at s3 blobstore
property also.

**Comment by mfine30** [comment]
Hey @marcus-sds looks like you solved this. If it's still a problem, feel free to re-open the issue.
