### ISSUE TITLE
Job properties should be specified on job level

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh-deployment#286]
Right now properties for jobs are specified on instance group level ([this is deprecated btw](https://bosh.io/docs/manifest-v2/#instance-groups)) which makes it impossible to override a particular property for a specific job.

For example [here](https://github.com/cloudfoundry/bosh-deployment/blob/9b02de6/vsphere/cpi.yml#L44) properties are specified for all jobs. If I want to use different proxy settings for vsphere_cpi job (which needs to connect to vSphere API) and director (which needs to connect to Internet) I have to redefine [the rest of properties](https://github.com/cloudfoundry/bosh-deployment/blob/9b02de6/vsphere/cpi.yml#L46-L57) (+ [ntp + agent + blobstore + nats](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/35b7a3a/jobs/vsphere_cpi/spec#L74-L153)) for a specific job.

**Comment by deniseyu** [comment]
Hi @giner thanks for raising this! This sounds pretty reasonable to us. I've created a story in our public tracker for this work: https://www.pivotaltracker.com/story/show/162018723

**Comment by dpb587-pivotal** [comment]
We haven't changed how properties are configured yet. In general, it's a pretty low priority since it's not trivial (there are many ops files and external ops files out there which would likely end up breaking).

**Comment by giner** [comment]
At the same time the longer we wait the bigger the change becomes due to growing number of external ops files.

**Comment by bengerman13** [comment]
is there any movement on this? this feature has now [been removed entirely ](https://github.com/cloudfoundry/bosh/releases/tag/v270.6.0)

**Comment by aeijdenberg** [comment]
Looks like there is at least some movement, e.g. I can see both a [commit](https://github.com/cloudfoundry/bosh-deployment/commit/fa713b8329160590c40ef08f9692363f7987e23d) to fix this, then another to [revert it](https://github.com/cloudfoundry/bosh-deployment/commit/f5a9be3e267dbbb2fbb0f0011e605beaabdada6a) within the last 24 hours, but I can't see any comments as to why it was reverted...

Can @jfmyers9 or @charleshansen comment further?

**Comment by charleshansen** [comment]
@aeijdenberg We didn't fully appreciate that removing the feature entirely in the director was going to break bosh-deployment for people who use inner/outer bosh. Once 270.6.0 was published, our pipelines went red and we attempted to move the properties to the job level. In the end we couldn't move the properties (more below) and instead added instance_group level properties back into the director. There should be a patch release of the director soon.

More on why we couldn't move the properties to the job level:

We got job-level properties to work on a vanilla bosh lite and pushed a commit, but then we realized that some director related jobs relied on instance_group level properties. For example, the google cpi will use properties from the director and the blobstore and the registry(?!) in addition to its own properties. In theory we could just copy all those properties to the google_cpi job, but that only works if no other ops files change any of those properties. To do this right, we would need to make the other ops files much more complicated. Even then we were almost certainly going to break a bunch of people. This meant we had to revert it.

**Comment by aeijdenberg** [comment]
@charleshansen - thanks for sharing the info with us. Sounds like a tricky one to resolve!

Do you know if the patch will come through as a new version tag? A recent change to the way tagging is done to this repository is causing havoc for our CI/CD. Tags are being mutated to point to different commits which I've been unable to see any meaningful updates on. :( https://github.com/cloudfoundry/bosh-deployment/issues/367

**Comment by jfmyers9** [comment]
It's unfortunate that `tags` are exposed as `releases` for Github. Our intention is still that the stable way to consume bosh-deployment is the `master` branch. We have added tagging for internal reasons to track when specific versions of BOSH make it into bosh-deployment. There is some oddity with that right now, where it will mutate the tag every time the BOSH release get's recompiled i.e. a new stemcell. These tags are not meant to be consumed by users of bosh-deployment.

This change will come through soon when `270.7.0` of BOSH gets cut.

**Comment by aeijdenberg** [comment]
@jfmyers9 - looks like `270.7.0` has now been cut. Is this now safe to take with regards to this issue? I'm unable to see reference in the release notes in this repo to this issue being resolved.

**Comment by charleshansen** [comment]
It should be safe to use 270.7.0 now. I agree there is nothing in the release notes. @mfine30 do you want to add a note in the bosh release notes for 270.7.0 saying that instance properties are enabled? It is kinda weird since we don't want people to use them outside of bosh-deployment.
