### ISSUE TITLE
bump bpm to 0.10.0

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-deployment#290]
this will solve the following issues we have.
https://github.com/cloudfoundry-incubator/bpm-release/issues/67

**Comment by mfine30** [comment]
Thanks for raising this. We'll be bumping it shortly in: https://www.pivotaltracker.com/story/show/159861541

**Comment by dpb587-pivotal** [comment]
Closing - bumped to 0.11.0 in https://github.com/cloudfoundry/bosh-deployment/commit/8c350146d8dfc45e694d3d947be643e7eb0ba54f
