### ISSUE TITLE
bosh create-env failed

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh-deployment#294]
I used the latest commit dosh-deployment and tried to deploy it on a ubuntu 16.04 server. The error below alerted:

```
bosh2 create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o uaa.yml \
  -o credhub.yml \
  -o jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name=bosh-lite \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork \
  -v admin_password=admin
```

```
Deployment manifest: '/root/workspace/useful-scripts/bosh-lite/bosh-deployment/bosh.yml'
Deployment state: './state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:00)
  Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:02)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:01)
  Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-warden-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
  Validating release 'uaa'... Finished (00:00:01)
  Downloading release 'credhub'... Skipped [Found in local cache] (00:00:00)
  Validating release 'credhub'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:02)
Finished validating (00:00:10)

Started installing CPI
  Compiling package 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'... Finished (00:00:15)
  Compiling package 'golang-1.10-darwin/9eacb8fc6b1b693e4280be4e916e2000f375bfbf'... Finished (00:00:16)
  Compiling package 'virtualbox_cpi/491b894473950429800ed1ce9dbe1940aac37307'... Finished (00:00:18)
  Installing packages... Finished (00:00:04)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:55)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/97.12'... Finished (00:00:24)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-7fcbfe38-29ae-4cb6-7ed2-111b009062ce'... Finished (00:00:09)
  Waiting for the agent on VM 'vm-b7cd0629-b07e-479a-41e5-3e74c7e4f631' to be ready... Finished (00:00:29)
  Creating disk... Finished (00:00:00)
  Attaching disk 'disk-1483acf0-83e8-44fd-6c4e-67fbe58ccc4e' to VM 'vm-b7cd0629-b07e-479a-41e5-3e74c7e4f631'... Finished (00:00:05)
  Rendering job templates... Failed (00:00:04)
Failed deploying (00:00:51)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

**Deploying:
  Building state for instance 'bosh/0':
    Rendering job templates for instance 'bosh/0':
      Rendering templates for job 'garden/3fb1853c634dac50f667e2bebe899d00098d1331272bfdb59e2e6171ce862ca5':
        Rendering template src: bin/garden_start.erb, dst: bin/garden_start:
          Rendering template src: /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/bosh-release-job366135021/templates/bin/garden_start.erb, dst: /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/rendered-jobs634437470/bin/garden_start:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/erb-renderer743851301/erb-render.rb /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/erb-renderer743851301/erb-context.json /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/bosh-release-job366135021/templates/bin/garden_start.erb /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/rendered-jobs634437470/bin/garden_start', stdout: '', stderr: '/root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/erb-renderer743851301/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/bosh-release-job366135021/templates/bin/garden_start.erb' for garden/0 (line unknown: #<SyntaxError: /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/bosh-release-job366135021/templates/bin/garden_start.erb:4: syntax error, unexpected ';' (RuntimeError)
-; _erbout.concat "\n#!/usr/bin...
  ^>)
	from /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/erb-renderer743851301/erb-render.rb:175:in `render'
	from /root/.bosh/installations/0c4f71ed-2e57-48c2-63da-93fc65c5107f/tmp/erb-renderer743851301/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1**
```

**Comment by jfmyers9** [comment]
Hi @qibobo,

I just validated that this appears to work on my machine. `bosh create-env` uses the system ruby on your local workstation to template the configuration files used on the director. What version of ruby is installed on your local machine? Could you check that you are using an up to date ruby and erb version?

Let me know if that helps,

@jfmyers9, CF BOSH

**Comment by qibobo** [comment]
@jfmyers9  Thanks for your response.
Previously my ruby version was ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu] when I submitted this issue. Today I upgraded it to ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux] and tried again, error is still here:

```
Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-7dd18190-5c76-47c3-7cf7-3f416844cf78'... Finished (00:00:01)
  Waiting for the agent on VM 'vm-45232b22-2b60-4e79-4a2b-c7be6d90dee8' to be ready... Finished (00:00:33)
  Creating disk... Finished (00:00:00)
  Attaching disk 'disk-e9d6ad86-432f-409a-5542-eda6260266d4' to VM 'vm-45232b22-2b60-4e79-4a2b-c7be6d90dee8'... Finished (00:00:05)
  Rendering job templates... Failed (00:00:06)
Failed deploying (00:00:47)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'bosh/0':
    Rendering job templates for instance 'bosh/0':
      Rendering templates for job 'garden/3fb1853c634dac50f667e2bebe899d00098d1331272bfdb59e2e6171ce862ca5':
        Rendering template src: bin/bpm-pre-start.erb, dst: bin/bpm-pre-start:
          Rendering template src: /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb, dst: /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/rendered-jobs211483038/bin/bpm-pre-start:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/erb-renderer204522624/erb-render.rb /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/erb-renderer204522624/erb-context.json /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/rendered-jobs211483038/bin/bpm-pre-start', stdout: '', stderr: '/root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/erb-renderer204522624/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb' for garden/0 (line unknown: #<SyntaxError: /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb:22: syntax error, unexpected ';' (RuntimeError)
.../vcap/data/rep/shared_data') -; _erbout.<< "\nif ! grep -q \...
...                              ^
/root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb:28: syntax error, unexpected keyword_end
; - end } -; _erbout.<< "\n\nmkdir -...
    ^~~
/root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/bosh-release-job611843117/templates/bin/bpm-pre-start.erb:31: syntax error, unexpected end-of-input, expecting '}'
; _erbout
         ^>)
	from /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/erb-renderer204522624/erb-render.rb:174:in `render'
	from /root/.bosh/installations/dbfa885d-a7b1-4b5a-7133-b0229ad41443/tmp/erb-renderer204522624/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```

**Comment by jfmyers9** [comment]
Hi @qibobo,

What version of the bosh CLI are you using? Could you try using the [latest version of the CLI](https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.2.2) and see if that fixes your issue?

Best,

@jfmyers9 && @mikexuu, CF BOSH

**Comment by qibobo** [comment]
@jfmyers9  After I upgraded to the latest version of bosh cli, the issue fixed. Thanks.

**Comment by jfmyers9** [comment]
I'm glad that worked for you. :+1:

**Comment by mwaseemalvi** [comment]
Hello, I am new and I am trying to create env in ubuntu18.04. I am using bosh cli5.5.1 and ruby 2.5.1. I have installed virtualbox 6.0. When I am trying to create env, I am getting following errors. Could you please provide me details. Error log is given below.
sudo ./bosh-deployment/virtualbox/create-env.sh


==\
===> Creating BOSH Director
==/

Deployment manifest: '/home/ubuntu/bosh-env/virtualbox/bosh-deployment/bosh.yml'
Deployment state: '/home/ubuntu/bosh-env/virtualbox/state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:02)
  Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:05)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:04)
  Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-warden-cpi'... Finished (00:00:02)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
  Validating release 'uaa'... Finished (00:00:05)
  Downloading release 'credhub'... Skipped [Found in local cache] (00:00:00)
  Validating release 'credhub'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:09)
Finished validating (00:00:49)

Started installing CPI
  Compiling package 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'... Finished (00:00:43)
  Compiling package 'golang-1.10-darwin/9eacb8fc6b1b693e4280be4e916e2000f375bfbf'... Finished (00:00:43)
  Compiling package 'virtualbox_cpi/491b894473950429800ed1ce9dbe1940aac37307'... Finished (00:00:33)
  Installing packages... Finished (00:00:12)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:02:14)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/315.36'... Finished (00:04:53)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-95dd03ef-76bb-474b-5391-b5d1721a1645'... Failed (00:01:18)
Failed deploying (00:01:18)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-95dd03ef-76bb-474b-5391-b5d1721a1645':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{1897bdfe-541f-44ea-5f59-0493e626ffe5}}': Starting VM: Retried '30' times: Running command: 'VBoxManage startvm vm-09a79a2d-d48f-4ca7-66bc-a2194edd9ce4 --type headless', stdout: 'Waiting for VM \"vm-09a79a2d-d48f-4ca7-66bc-a2194edd9ce4\" to power on...\n', stderr: 'VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole\n': exit status 1","ok_to_retry":false}

Exit code 1


Thanks
