### ISSUE TITLE
the following commit reverts back to trusty

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-deployment#298]
@jrussett 
the last commit reverted xenial back to trusty.
https://github.com/cloudfoundry/bosh-deployment/commit/69503cb9b0a0917aaf083b6067d72b0bd11a6bca#diff-dd8d3a2e678591beb8384fc074890c04

i don't think this was intended.

**Comment by jrussett** [comment]
@ramonskie thanks for the catch, we're updating it right now.

**Comment by jrussett** [comment]
@ramonskie it's been reverted back to using a xenial-compiled release in this commit:
https://github.com/cloudfoundry/bosh-deployment/commit/9ecbbbf53600570cfb282575abff83b78f289c99

Thanks again for catching this!
@jrussett, CF BOSH

**Comment by ramonskie** [comment]
no problem our bucc ci just failed for some very strange reason so that's why we catched it pretty quick
