### ISSUE TITLE
1 of 3 post-start scripts failed. Failed Jobs: credhub

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/bosh-deployment#303]
hi every one i am trying to deploy bosh-deployment on openstack IaaS. But unfortunately for the first time i am encountering error in credhub.

Error
Deploying:
  Running the post-start script:
    Sending 'get_task' to the agent:
      Agent responded with error: Action Failed get_task: Task fe448a2f-35f3-4a38-6085-204e0361f8b2 result: 1 of 3 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa, director.

Before i have deployed many director with UAA and Credhub many-times, but i did'nt encounter above error. For your reference i have attached deployment script and credhub log.

bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state ./state.json \
  -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
  -o ~/workspace/bosh-deployment/uaa.yml \
  -o ~/workspace/bosh-deployment/credhub.yml \
  -o ~/workspace/bosh-deployment/jumpbox-user.yml \
  -o ~/workspace/bosh-deployment/openstack/disable-readable-vm-names.yml \
  -o ~/workspace/bosh-deployment/local-dns.yml \
  --vars-store ./creds.yml \
  -v director_name=kubo \
  -v internal_ip=10.0.20.90 \
  -v internal_gw=10.0.20.1 \
  -v internal_cidr=10.0.20.0/24 \
  -v auth_url=http://xxx.xxx.xxx.xxx:5000/v3 
  -v az=nova 
  -v default_key_name=bosh 
  -v default_security_groups=[bosh] 
  -v net_id=82959d61-0e6c-4e5d-8569-0e8702d178b5 
  -v openstack_password=xxxxxx 
  -v openstack_username=xxxxxx 
  -v openstack_domain=default 
  -v openstack_project=xxxxx 
  -v private_key=xxxxxxxx/bosh.pem 
  -v region=RegionOne

[pre-start.stdout.log](https://github.com/cloudfoundry/bosh-deployment/files/2509047/pre-start.stdout.log)
[pre-start.stderr.log](https://github.com/cloudfoundry/bosh-deployment/files/2509048/pre-start.stderr.log)
[post-start.stdout.log](https://github.com/cloudfoundry/bosh-deployment/files/2509049/post-start.stdout.log)
[credhub.stdout.log](https://github.com/cloudfoundry/bosh-deployment/files/2509050/credhub.stdout.log)
[credhub.log](https://github.com/cloudfoundry/bosh-deployment/files/2509051/credhub.log)

thanks in advance

**Comment by dpb587-pivotal** [comment]
`credhub.log` contains the following error and a suggestion for how you can fix it:

> java.lang.RuntimeException: The encryption keys provided cannot decrypt any of the 24 value(s) in the database. Please make sure you've provided the necessary encryption keys.

For more assistance, please check with the CredHub team since they'll have more familiarity with the problems you're running into if they're specific to the credhub release.
