### ISSUE TITLE
config_server job fails with external postgres

### ISSUE THREAD

**Issue by rokejung** [cloudfoundry/bosh-deployment#325]
I have an ops file to configure external postgres for uaa, credhub and config_server jobs. I created bosh, credhub, uaa and config_server tables in the external postgres DB. BOSH deployment fails. Based on the job log files, uaa and and credhub connected to the remote postgres and started successfully. However, config_server tried to connect to local postgres and failed.

panic: Unable to start server
Failed to create data store: Failed to open connection to DB: Could not get DB version: dial tcp 127.0.0.1:5432: getsockopt: connection refused

goroutine 1 [running]:
panic(0x7cd440, 0xc82011e1d0)
       /var/vcap/data/packages/golang/7cb93f2c813418b74eeb6aeeeb066905a609212c/src/runtime/panic.go:481 +0x3e6
main.main()

/var/vcap/jobs/config_server/config/config.json has the correct database information though.

{"port":8080,"certificate_file_path":"/var/vcap/jobs/config_server/config/cert","private_key_file_path":"/var/vcap/jobs/config_server/config/key","ca_certificate_file_path":"/var/vcap/jobs/config_server/config/ca_certificate","ca_private_key_file_path":"/var/vcap/jobs/config_server/config/ca_private_key","jwt_verification_key_path":"/var/vcap/jobs/config_server/config/jwt_verification_key","store":"database","database":{"adapter":"postgres","user":"postgres","password":"postgres","host":"9.21.107.54","port":5432,"db_name":"config_server","connection_options":{"max_open_connections":32,"max_idle_connections":10}}}

**Comment by dpb587-pivotal** [comment]
Hello - you should remove the `misc/config-server.yml` ops file from your `create-env` command. It does not support external databases and is used primarily for development. The `credhub.yml` ops file provides you with a much more functional implementation of the config server, so you should keep that instead.

Out of curiosity, was there documentation somewhere which recommended the use of `config-server.yml`? We should update docs to make its purpose more clear.

**Comment by dpb587-pivotal** [comment]
I see thanks. I'll see if we can clarify the docs.
