### ISSUE TITLE
Failed to deploy director because of precompiled releases for differing stemcell major versions 

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/bosh-deployment#332]
Hi, 
We are getting the following error when we try to deploy a bosh-lite director in our CI using latest `bosh-deployment`:

```
Task 56552 | 17:41:51 | Preparing deployment: Preparing deployment (00:00:01)
Task 56552 | 17:41:54 | Error: 
Can't use release 'bpm/0.12.3'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/250.4':
 - 'bpm/d139b63561eaa3893976416be9668dea539bf17d'
 - 'golang/27413c6b5a88ea20a24a9eed74d4b090b7b88331'
Can't use release 'bosh/268.6.0'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/250.4':
 - 'bosh-gcscli/a03b1fc29fd357b8e3023193c87ae9ee49db052965efe5b3d9bff3538ed2df4b'
 - 'davcli/100c52066493ef0d766c464c9cdd811c902a555013543bd16b62cf59ba5c72eb'
 - 'director/ece3294f1df40691f2ed44ce709a13db4be3da4327836db15598e6f1c2b5339f'
 - 'gonats/a32f561770ebdc422c2f9955c7614c23900b9edc62aec51a6b48adc636516802'
 - 'health_monitor/5741e1e4f409d5cfe168d77e01e36aec289d61128d9e72851c37b3d1e022c3f0'
 - 'libpq/b3fead55dd7c9fa83be2412b24db84d2b04dbdb5dd0583ee7e9afddbb200659a'
 - 'mysql/de7350b5d6d835f758a62c0b3a8f07d3f0150d67abfa0da3967bd1127fada4c6'
 - 'nginx/d9c13905876ac2bc3f62657048750257794ecc53121ad7cd92583d3ef292b8b8'
 - 'postgres-10/c4167f3ba3a46ff5fb147098d87b9d6001ea357459133a7cc0c21aad36d4a1bc'
 - 'postgres-9.4/ee3022bfae2cb7f7454aed9e28fe7715765b9a0086ef2045219f7a4e16baca81'
 - 'powerdns/95d1ce42da1bbaa19021bcaa295ed4f0f05e82c44b40638fcc934d91d212d2af'
 - 'registry/1cb5259ea0a3f50ed034f920e694f5431835ad55c221d491b22178298de56faf'
 - 'ruby-2.4-r5/726cbb2214e138b576700db6a30698edb2b994e2'
 - 's3cli/4b6a4e65f277e1e4cdd9bfd8330de14ea28e9e5762a304f2d3a35f47958d7376'
 - 'verify_multidigest/2405293bf44933ac48362d7e109fc38ea4469b962cf62715533ecca53c28bf7b'
Can't use release 'bosh-warden-cpi/40'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/250.4':
 - 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'
 - 'warden_cpi/5a07ecf85c489cd4c32ae26d3092513027e14b86'
``` 

Looking at the [bosh.yml](https://github.com/cloudfoundry/bosh-deployment/blob/a635dc688dc380b93c5174badda09365aa0ac157/bosh.yml#L7) it seems like a recent [commit](https://github.com/cloudfoundry/bosh-deployment/commit/f55656229b2556795f7b3ae0d83bd78b678e507f) updated the precompiled stemcell version of just one of the releases, so now we have `bosh` compiled for `250.*` and `bpm` compiled for `170.*` which I think explains the error we are observing. 

Indeed, when I changed the bosh precompiled version back to `170.9` deployment succeeded. Can you fix this pls?

**Comment by BooleanCat** [comment]
@georgethebeatle Looks like this was fixed some time last week - I think we can close this.

**Comment by jfmyers9** [comment]
Going to close this as we believe this to be fixed. Please feel free to reopen if you continue to see this as an issue.

**Comment by Callisto13** [comment]
Hey @jfmyers9 we are seeing this again after switching from lite stemcell 250.29 to 315.13 using bosh deployment master (293ae1f):

```
Error: 
Can't use release 'bosh-warden-cpi/40'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/315.13':
 - 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'
 - 'warden_cpi/5a07ecf85c489cd4c32ae26d3092513027e14b86'
```

**Comment by jfmyers9** [comment]
Hi @Callisto13,

I just successfully ran the `create-env.sh` script successfully on the master branch. Can you provide us with the operations files that you used to create the director?

Best,

@jfmyers9

**Comment by Callisto13** [comment]
Hey @jfmyers9, we use a bunch of custom ops files in our ci. I have thrown them all together in a gist [here](https://gist.github.com/Callisto13/b56f2b059ea7b94daa5554ea4438efee). The main thing we do is switch out garden to test we haven't broken you, and throw in the networking release.
I was able to run a successful create env on my local mac, but this is failing pretty consistently in [our ci](https://garden.ci.cf-app.com/teams/main/pipelines/main/jobs/boshlite-gats/builds/457). Let me know if you can't see that and I will add your github team (also tell me your github team!).

**Comment by Callisto13** [comment]
@jfmyers9 We managed to get the pipeline moving again by blowing away the boshlites and deploying from scratch, so obviously this is not urgent anymore. May still be of interest for the rolling upgrade usecase.
Thanks!

**Comment by h4xnoodle** [comment]
Thanks for updating @Callisto13 and we'll keep an eye out as well.
