### ISSUE TITLE
UAA auto-bump doesn't escape numbers correctly

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-deployment#337]
The recent [auto-bump](https://github.com/cloudfoundry/bosh-deployment/commit/420df8c8c03a33314865c410cf3d60cd20fb353d) changed `"64.0"` to `64`. Therefore, deploying fails with 
```
Task 2070 | 10:59:21 | Preparing deployment: Preparing deployment (00:00:01)
                     L Error: Release version 'uaa/64' doesn't exist
```

**Comment by mfine30** [comment]
Looks like this commit went through and fixed it
