### ISSUE TITLE
Bump AWS CPI release to version 74

### ISSUE THREAD

**Issue by jdesulme** [cloudfoundry/bosh-deployment#344]
Currently, the AWS CPI release is at version 73. I would like to request that this is increased to [version 74 ](https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v74) so we can take advantage of the newer instance types. In addition, improvement to the process would be to have the CI Bot automatically add the latest version when a new version is tagged in the AWS CPI project.

**Comment by mfine30** [comment]
Hey @jdesulme thanks for the poke. We are planning to bump the AWS CPI as part of this story here: https://www.pivotaltracker.com/story/show/164639113. Should be getting to it in the short future

**Comment by jdesulme** [comment]
Thanks @mfine30 I'm looking forward to it!
