### ISSUE TITLE
UAA startup issue

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-deployment#346]
We're having an issue with the uaa.yml ops file. When we deploy bosh-deployment (bb2e14e6fd1e17053fbbaac4fd92435cedc3ccc7) using UAA 71.0 on stemcell 250.21, the UAA starts up, becomes responsive on :8443, but monit never realizes this. It keeps repeatedly trying to hit http://<local-ip>:8443/healthz, but gets a 400, because the endpoint requires TLS. This seems to be due to the uaa.yml ops file setting the UAA's http port to -1, disabling non-tls traffic inbound.

Not sure if this is a uaa issue, a bosh issue, or a stemcell issue. When i try to make monit use `https` or configure any ssl options for the protocol check, i get syntax issues around `https` or `ssl`. If we override the ops file to specify a non-tls port, the release configures the health check on `:8080` which is then open, and everything works. I'd rather not have to enable insecure http just to have our UAA start up.

I'm also not sure what caused this to occur, since nothing seems to have changed in the release related to this behavior, or in bosh-deployment. When we first encountered this, we went from UAA 60.2 to UAA 71.0,  trusty 3586.91 stemcell  to xenial 250.21, and bosh-deployment ba03a10581182bbf29efa586040f16064ab92f7d to bb2e14e6fd1e17053fbbaac4fd92435cedc3ccc7.

**Comment by geofffranks** [comment]
Downgrading to uaa 64.0 and removing my ops file to re-enable the http-specific port was successful. The health check is still set up for :8443, but somehow works from monit's perspective.

When I curled :8443 using http rather than https, I get this output which somehow isn't a curl failure, despite not having the right protocol, or any http response:

```
# curl localhost:8443/healthz -vvv -f
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*
>
* Connection #0 to host localhost left intact
P
```

**Comment by h4xnoodle** [comment]
@geofffranks there are currently issues with all UAA releases after and including v68. Bosh-deployment will be updated to use the latest when we have heard the issue is fixed. Thanks!
