### ISSUE TITLE
Bump garden-runc to something recent?

### ISSUE THREAD

**Issue by Callisto13** [cloudfoundry/bosh-deployment#350]
Hi there folks!

Just wondering what your schedule is for bumping garden-runc-release. You have been on [1.16.3](https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh-lite.yml#L5-L8) for a while, can I entice you on to a newer version?

**Comment by Callisto13** [comment]
cc @yulianedyalkova

**Comment by mrosecrance** [comment]
We don't have an official schedule. As far as I know it's historically been a when it's too painfully old (which is seems like it now is) but I think we should just automate it. We already automate pulling in the latest garden and compiling it but for some reason it looks we build it and then just ignore it.

**Comment by Callisto13** [comment]
Hey Maya 👋 

Automating would be cool. As you probs remember, we have a job in our pipeline to ensure latest garden releases work with bosh lite, so hopefully we are well set up to catch anything nasty before it would get to you.

**Comment by h4xnoodle** [comment]
We've now automated this.
