### ISSUE TITLE
Issue create env 

### ISSUE THREAD

**Issue by mwaseemalvi** [cloudfoundry/bosh-deployment#353]
Hello, I am new and I am trying to create env in ubuntu18.04. I am using bosh cli5.5.1 and ruby 2.5.1. I have installed virtualbox 6.0. When I am trying to create env, I am getting following errors. Could you please provide me details. Error log is given below.
 sudo ./bosh-deployment/virtualbox/create-env.sh

==
 ===> Creating BOSH Director
 ==/

Deployment manifest: '/home/ubuntu/bosh-env/virtualbox/bosh-deployment/bosh.yml'
 Deployment state: '/home/ubuntu/bosh-env/virtualbox/state.json'

Started validating
 Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
 Validating release 'bosh'... Finished (00:00:01)
 Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
 Validating release 'bpm'... Finished (00:00:02)
 Downloading release 'bosh-virtualbox-cpi'... Skipped [Found in local cache] (00:00:00)
 Validating release 'bosh-virtualbox-cpi'... Finished (00:00:05)
 Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
 Validating release 'garden-runc'... Finished (00:00:04)
 Downloading release 'bosh-warden-cpi'... Skipped [Found in local cache] (00:00:00)
 Validating release 'bosh-warden-cpi'... Finished (00:00:02)
 Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
 Validating release 'os-conf'... Finished (00:00:00)
 Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
 Validating release 'uaa'... Finished (00:00:05)
 Downloading release 'credhub'... Skipped [Found in local cache] (00:00:00)
 Validating release 'credhub'... Finished (00:00:01)
 Validating cpi release... Finished (00:00:00)
 Validating deployment manifest... Finished (00:00:00)
 Downloading stemcell... Skipped [Found in local cache] (00:00:00)
 Validating stemcell... Finished (00:00:09)
 Finished validating (00:00:49)

Started installing CPI
 Compiling package 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'... Finished (00:00:43)
 Compiling package 'golang-1.10-darwin/9eacb8fc6b1b693e4280be4e916e2000f375bfbf'... Finished (00:00:43)
 Compiling package 'virtualbox_cpi/491b894473950429800ed1ce9dbe1940aac37307'... Finished (00:00:33)
 Installing packages... Finished (00:00:12)
 Rendering job templates... Finished (00:00:00)
 Installing job 'virtualbox_cpi'... Finished (00:00:00)
 Finished installing CPI (00:02:14)

Starting registry... Finished (00:00:00)
 Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/315.36'... Finished (00:04:53)

Started deploying
 Creating VM for instance 'bosh/0' from stemcell 'sc-95dd03ef-76bb-474b-5391-b5d1721a1645'... Failed (00:01:18)
 Failed deploying (00:01:18)

Stopping registry... Finished (00:00:00)
 Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
 Creating instance 'bosh/0':
 Creating VM:
 Creating vm with stemcell cid 'sc-95dd03ef-76bb-474b-5391-b5d1721a1645':
 CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{1897bdfe-541f-44ea-5f59-0493e626ffe5}}': Starting VM: Retried '30' times: Running command: 'VBoxManage startvm vm-09a79a2d-d48f-4ca7-66bc-a2194edd9ce4 --type headless', stdout: 'Waiting for VM "vm-09a79a2d-d48f-4ca7-66bc-a2194edd9ce4" to power on...\n', stderr: 'VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole\n': exit status 1","ok_to_retry":false}

Exit code 1

Thanks

**Comment by h4xnoodle** [comment]
Hello @mwaseemalvi there is currently an issue with using bosh-lite on VirtualBox 6+. Please try downgrading to 5.2 (known working version). We have the following story to address the problem: https://www.pivotaltracker.com/story/show/166461459

**Comment by mwaseemalvi** [comment]
Hi, What is the solution or way out regarding this problem, I have created another ticket as well with different versions.
https://github.com/cloudfoundry/bosh-deployment/issues/355#issuecomment-500620438

**Comment by h4xnoodle** [comment]
In reading all those tickets, I can only say that it must be your machine's configuration of virtualbox. You've had quite a lot of trouble getting it setup so far. Are you able to use virtualbox for other functions such as launching an ubuntu iso?

**Comment by mwaseemalvi** [comment]
Could please provide me how to setup Bosh and director step by step guideline?

**Comment by h4xnoodle** [comment]
@mwaseemalvi you're already running the correct script to setup the bosh director in virtualbox. There is an issue with your virtualbox installation. Please try correcting that before proceeding. If you have another computer to try that would likely help. You could also use a cloud provider directly, and use the free tier if you wish to not spend money.

Closing this because it's not an issue with bosh.

**Comment by mwaseemalvi** [comment]
Could you please mention which virtual box is suitable on Ubuntu 18.04 with bosh cli 5.5.1.

**Comment by h4xnoodle** [comment]
We have now updated the virtualbox CPI to work with versions beyond 5.1. Can you try pulling bosh-deployment and running the create-env script again with your version of virtualbox?
