### ISSUE TITLE
Bosh Director Deployment - Create Env

### ISSUE THREAD

**Issue by mwaseemalvi** [cloudfoundry/bosh-deployment#355]
Hello,
 Hello, I am trying to create env in ubuntu18.04. I am using bosh cli5.5.1 and ruby 2.5.1. I have installed virtualbox 5.1.38. When I am trying to create env, I am getting following errors. Could you please provide me details. Error log is given below. I am following the same guideline which is mentioned in this link(https://bosh.io/docs/quick-start/). Please confirm me before executing the below command, should I need to change/update any config file or any script file.

sudo ./bosh-deployment/virtualbox/create-env.sh

==\
===> Creating BOSH Director
==/

Deployment manifest: '/home/ubuntu/bosh-env/virtualbox/bosh-deployment/bosh.yml'
Deployment state: '/home/ubuntu/bosh-env/virtualbox/state.json'

Started validating
  Downloading release 'bosh'... Finished (00:03:27)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Finished (00:03:25)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-virtualbox-cpi'... Finished (00:00:34)
  Validating release 'bosh-virtualbox-cpi'... Finished (00:00:04)
  Downloading release 'garden-runc'... Finished (00:05:07)
  Validating release 'garden-runc'... Finished (00:00:02)
  Downloading release 'bosh-warden-cpi'... Finished (00:02:55)
  Validating release 'bosh-warden-cpi'... Finished (00:00:01)
  Downloading release 'os-conf'... Finished (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'uaa'... Finished (00:06:49)
  Validating release 'uaa'... Finished (00:00:04)
  Downloading release 'credhub'... Finished (00:02:29)
  Validating release 'credhub'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:10:40)
  Validating stemcell... Finished (00:00:07)
Finished validating (00:36:09)

Started installing CPI
  Compiling package 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'... Finished (00:00:36)
  Compiling package 'golang-1.10-darwin/9eacb8fc6b1b693e4280be4e916e2000f375bfbf'... Finished (00:00:30)
  Compiling package 'virtualbox_cpi/491b894473950429800ed1ce9dbe1940aac37307'... Finished (00:00:34)
  Installing packages... Finished (00:00:14)
  Rendering job templates... Finished (00:00:00)
  Installing job 'virtualbox_cpi'... Finished (00:00:00)
Finished installing CPI (00:01:57)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/315.36'... Finished (00:00:30)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-d7f02922-4ace-4b92-44fb-988171d7cb68'... Failed (00:01:21)
Failed deploying (00:01:21)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-d7f02922-4ace-4b92-44fb-988171d7cb68':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{bf624af8-4aec-430b-49f1-113b9bc4d90e}}': Starting VM: Retried '30' times: Running command: 'VBoxManage startvm vm-d011d7b1-d5b8-4fc6-7870-430a0a190ed3 --type headless', stdout: 'Waiting for VM \"vm-d011d7b1-d5b8-4fc6-7870-430a0a190ed3\" to power on...\n', stderr: 'VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole\n': exit status 1","ok_to_retry":false}

Exit code 1

**Comment by mwaseemalvi** [comment]
Ubuntu version is 16.04 not 18.04

**Comment by jfmyers9** [comment]
Hey @mwaseemalvi,

It appears that you already have an open issue on #354. Let's consolidate the conversation there. I'm going to close this issue in the meantime.

Best,

@jfmyers9

**Comment by mwaseemalvi** [comment]
But I have the problem with other versions too. Please let me provide the solution or way out how can I resolved it.
