### ISSUE TITLE
Consider increasing memory for VirtualBox

### ISSUE THREAD

**Issue by SocalNick** [cloudfoundry/bosh-deployment#356]
Hi folks!

I recently followed the instructions for installing BOSH onto a VirtualBox VM and then attempted to run Cloud Foundry using cf-deployment. I got everything deployed but as soon as I attempted to push an application, the staging process hung and I started getting 404s when interacting with the the CF API. Digging into the problem, I found the VirtualBox VM swapping heavily, seems the days of 4GB to run Cloud Foundry might be long gone! Increasing to 8GB VirtualBox VM got things going, I think I was hovering a little over 5GB used when CF is deployed and staging an application.

I know this isn't technically a BOSH issue, but if folks follow the docs to deploy BOSH and then CF, they'll likely have a bad day. Maybe we could add an additional operations file that is documented to increase the memory if the operator is going to be installing CF?

Nick

**Comment by h4xnoodle** [comment]
Hi @SocalNick, thanks for bringing this to our attention.

Another project that may be of interest to you for using CF in a dev environment is https://github.com/cloudfoundry-incubator/cfdev. There are also some recommendations there for host machine resources.

In general bosh-deployment and its usage is for development/testing for bosh. We don't generally expect people to deploy CF locally in full. Are you also using the bosh-lite opsfile for cf-deployment? https://github.com/cloudfoundry/cf-deployment/blob/master/operations/bosh-lite.yml

Closing this as it's not an issue pertaining to bosh-deployment itself, more the usage afterwards. Hopefully cf-dev can be the better tool for you.

Thanks,
Rebecca, BOSH, Pivotal

**Comment by jfmyers9** [comment]
Hey @SocalNick,

After some internal discussions, we decided that we would try increasing the default virtualbox memory and cpu to their older values that used to be specified in the vagrant bosh-lite. Hopefully this helps a bit.

Best,

@jfmyers9, CF BOSH

**Comment by SocalNick** [comment]
Thanks Rebecca and Jim, I can definitely see it both ways, appreciate the default resource bump!
