### ISSUE TITLE
bosh.yml should specify stemcells for compiled releases

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/bosh-deployment#362]
We're trying to upgrade a BOSH lite deployed through a non-lite director and having some issues. The stemcell has been upgraded, but the director contains releases with the same version numbers compiled against an earlier stemcell. When deploying we get the following error:

```
Can't use release 'bpm/1.1.0'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/456.1':
 - 'bpm/5c2ff257e105bb48d670bfbdb83f39bb58765ae8'
 - 'bpm-runc/7e77f8d491425cfdbd45377f0d5d3ef0c0b766c2'
 - 'golang/408c40bbad364c359e0cdcf3959732f9b0df8469'
 - 'tini/3d7b02f3eeb480b9581bec4a0096dab9ebdfa4bc'
Can't use release 'bosh-warden-cpi/40'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/456.1':
 - 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'
 - 'warden_cpi/5a07ecf85c489cd4c32ae26d3092513027e14b86'
```

Adding the following hunk to the offending releases fixes the problem:
```
  stemcell:
    os: ubuntu-xenial
    version: 456.1
```

It would be nice if `bosh-deployment` did this for every compiled release it uses (including in ops files!)

/cc @kieron-pivotal

**Comment by belinda-liu** [comment]
Hey @gcapizzi,

It seems that the error you're seeing was a mismatch between the package's version and the deployed stemcell version, since some of the releases did not get properly bumped to the new 456 stemcell line (as mentioned in your other issue). We've properly bumped all of the releases now, and this issue should no longer appear. 

Thanks!

**Comment by kieron-pivotal** [comment]
Hi @belinda-liu,

We still saw this problem with the latest changes.

```
Task 83570 | 08:50:35 | Preparing deployment: Preparing deployment (00:00:01)
Task 83570 | 08:50:36 | Preparing deployment: Rendering templates (00:00:01)
Task 83570 | 08:50:37 | Error:
Can't use release 'bosh-warden-cpi/40'. It references packages without source code and are not compiled against stemcell 'bosh-google-kvm-ubuntu-xenial-go_agent/456.1':
 - 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'
 - 'warden_cpi/5a07ecf85c489cd4c32ae26d3092513027e14b86'
```

The director had golang-1.10-linux and warden_cpi releases compiled against an earlier stemcell.

Adding that stemcell hunk in the top comment fixed the deployment. So would it be possible to add stemcell details to all compiled releases as per the comments in https://github.com/cloudfoundry/bosh/issues/1620?

Thanks,
Kieron

**Comment by jfmyers9** [comment]
Hi @kieron-pivotal,

Are you sure you are seeing this on the latest commit of bosh-deployment? 2ab87e77fd03d86a9d5319d48d89790707a78d6a

All of the related releases should now be compiled against the `456.1` stemcell. Adding the `stemcell` block as suggested in #1620 isn't actually solving the issue, it is just hiding the fact that the release was not compiled against the correct stemcell.

Let us know if it continues to fail,

@jfmyers9 @belinda-liu, CF BOSH
