### ISSUE TITLE
bosh-lite ops-file uses packages compiled for an old stemcell

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/bosh-deployment#363]
The `bosh-lite.yml` ops-file is still using releases which were compiled for the `315.*` stemcell (see [here](https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh-lite.yml#L7) and [here](https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh-lite.yml#L15)). This seems to be a problem for other ops-files as well (see https://github.com/cloudfoundry/bosh-deployment/issues/361).

**Comment by belinda-liu** [comment]
Hey @gcapizzi,

Thanks for the catch. There was a bug in our autobumping pipeline that we just fixed. Everything should be up to date now.
