### ISSUE TITLE
SSL certificate duration option declared as a interpolated variable?

### ISSUE THREAD

**Issue by wildloop** [cloudfoundry/bosh-deployment#365]
Now it is not easy to change the duration of all generated certificates because one bosh operation (ops file) must match exactly one item of variables array:
```
Parsing release set manifest 'bosh.yml':
  Evaluating manifest:
    Expected to find exactly one matching array item for path '/variables/type=certificate' 
```

Something like that would be great:
```
variables:
- name: default_ca
  type: certificate
  options:
    common_name: ca
    is_ca: true
    duration: ((certificate_duration))
```

**Comment by h4xnoodle** [comment]
Hi @wildloop,

Are you looking to have a custom duration for each time you make a director or just looking to increase once? We could set a reasonable default instead of having a new opsfile/variable/input. What would be a reasonable default for you such that you don't need to change the value often?

Rebecca, BOSH

**Comment by wildloop** [comment]
I'm looking an easy way to to have a custom duration for all certificates for each time I make a director.
Now I have the ops file:
```
- type: replace
  path: /variables/name=default_ca/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=director_ssl/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=nats_ca/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=nats_server_tls/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=nats_clients_director_tls/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=nats_clients_health_monitor_tls/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=blobstore_ca/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=blobstore_server_tls/options?/duration?
  value: 3650

- type: replace
  path: /variables/name=credhub_ca/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=credhub_tls/options?/duration?
  value: 3650

- type: replace
  path: /variables/name=uaa_ssl/options?/duration?
  value: 3650
- type: replace
  path: /variables/name=uaa_service_provider_ssl/options?/duration?
  value: 3650
```
but I want be sure I set the custom duration for the all certificates generated in this deployment.

**Comment by jfmyers9** [comment]
Hi @wildloop,

We are hesitant to add a variable for `((certificate_duration))`` as there isn't a reasonable way for us to provide a default value that any invocation of `create-env` or `interpolate` can provide. For the reason, we see two ways to proceed:

* Increase the default duration to a different value, i.e. 2 years
* Provide an operations file in bosh-deployment that is similar to the one you have written above to allow users to configure the duration of any certs that may be provided.

Do any of those options work for you? Do you have any other ideas how we could expose this functionality without affecting the default case?

Best, 

@jfmyers9 && @xtreme-conor-nosal

**Comment by jostockley** [comment]
How about adding a command line option to create-env and interpolate, named --certificate-duration that would allow the default duration to be overridden.
For example:

bosh create-env mybosh --certificate-duration=3650 ...

Cheers,
Jo

**Comment by addisflava** [comment]
currently create-env  does not accept changing certificate duration at all 

```
Parsing release set manifest 'bosh.yml':
  Evaluating manifest:
    Getting all variables from variable definitions sections:
      Generating variable 'mbus_bootstrap_ssl':
        Failed to generate certificate, parameters are invalid:
          Unsupported certificate parameter 'duration'

Exit code 1

```
from the deployment 

```
variables:
- name: mbus_bootstrap_ssl
  options:
    alternative_names:
    - ((internal_ip))
    ca: default_ca
    common_name: ((internal_ip))
    duration: 3650

```

**Comment by jostockley** [comment]
I am asking that the bosh developers consider adding a new command line option (--certificate-duration) to allow us to override the default duration if one is not specified in the manifest.
I wasn't suggesting that the option was already present.

BTW: You need bosh cli 6+ to support the duration setting in manifests.

**Comment by h4xnoodle** [comment]
@jostockley 's suggestion of using bosh cli 6+ to add duration in the manifest is the solution.

We wouldn't put an option in the CLI itself as the manifest is the 'source of truth' for the deployment of the director. The CLI is enough of a 'director' to deploy the director. With any deployment, all config is expected to be in the manifest.

I think @wildloop 's opsfile could be amended to include a `((certificate_duration))` like @jfmyers9 and @xtreme-conor-nosal have suggested already is the preferred way to solve this problem. You can then supply `-v certificate_duration=xxxx` on the CLI.

```
- type: replace
  path: /variables/name=default_ca/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=director_ssl/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=nats_ca/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=nats_server_tls/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=nats_clients_director_tls/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=nats_clients_health_monitor_tls/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=blobstore_ca/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=blobstore_server_tls/options?/duration?
  value: ((certificate_duration))

- type: replace
  path: /variables/name=credhub_ca/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=credhub_tls/options?/duration?
  value: ((certificate_duration))

- type: replace
  path: /variables/name=uaa_ssl/options?/duration?
  value: ((certificate_duration))
- type: replace
  path: /variables/name=uaa_service_provider_ssl/options?/duration?
  value: ((certificate_duration))

bosh create-env [... opsfiles] -o <this file> -v certificate_duration=3650
```

As these options are already available, it doesn't make sense to add a CLI option that touches deployment-specific operations. You can also `create-env` without any certificates at all, and mapping a CLI option to manifests somehow would mean tight coupling between the CLI and some manifest.

Closing as there is already a solution here above.
