### ISSUE TITLE
GitHub release tags are being mutated by CI Bot (?)

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/bosh-deployment#367]
Hmm, our CI just notified me a commit has been pushed to `master` is tagged as: `270.5.0`

```
author: CI Bot
author_date: 2019-09-10 00:14:20 +0000
commit: 84287681c21b12ad15292ad5e8b4d8944144f32f
message: Bumping bosh to version 270.5.0
tags: 270.5.0
```

However our history in Concourse shows me that a different commit was tagged as `270.5.0` a few weeks ago:

```
author: CI Bot
author_date: 2019-08-31 00:58:40 +0000
commit: 4c3cd95759fdacd96df8dcbaec572373541fa133
message: Bumping bosh to version 270.5.0
tags: 270.5.0
```

Is this intentional? I was of the impression that tags (unlike branches) should be regarded as roughly immutable. I'd have thought that re-tagging a different commit to an existing tag in a public project would be roughly akin for force-pushing `master`, ie not good form.

In any case, this is making it very difficult for us to reason which is the legimate or correct release, and I'm hoping this is a bug in your `CI Bot`. I don't I've ever seen any other project do this...

(btw, I'm very happy to see this repo now actually get releases and tagging!)

Hmm - this commit looks like it might be the culprit:
https://github.com/cloudfoundry/bosh-deployment/commit/bd2abbef088284377e21a397076573db503c9b9a

**Comment by aeijdenberg** [comment]
An impact of this is that we are unable to use the Concourse `git-resource` to mirror this repository locally, we receive errors such as:

```
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
To ssh://xxxxxxxx/yyyyy/bosh-deployment.git
   fca68da..7fad441  HEAD -> master
 * [new tag]         270.6.0 -> 270.6.0
 ! [rejected]        270.5.0 -> 270.5.0 (already exists)
error: failed to push some refs to 'ssh://git@xxxxxxxx/yyyyy/bosh-deployment.git'
hint: Updates were rejected because the tag already exists in the remote.
```

I realise that we could likely set `force` attribute to `true` - however that isn't a good workaround.

**Comment by charleshansen** [comment]
After the team talked it over, bosh-deployment is only supposed to be consumed from master. We do not want to support people consuming tagged "releases". The tags were only added for internal consumption in a ci pipeline, which we don't really need. We are no longer tagging bosh-deployment at all, mutating tags should no longer be an issue.
