### ISSUE TITLE
Error "Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported" runnig create-env

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry/bosh-deployment#374]
Hi, I am trying to create a new bosh director on vSphere 5.5. With latest `bosh-deployment` repo, I am getting below error:

`CLI] 2019/11/05 21:30:32 ERROR - Error getting CPI info: CPI 'info' method responded with error: CmdError{"type":"Unknown","message":"Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported","ok_to_retry":false}
Error getting CPI info:
  CPI 'info' method responded with error: CmdError{"type":"Unknown","message":"Request version 'urn:pbm/6.7' and namespace 'urn:pbm' are not supported","ok_to_retry":false}`

Attached the error stack.
[error-stack.log](https://github.com/cloudfoundry/bosh-deployment/files/3812338/error-stack.log)

Appreciate any help!

Thanks,
Chandan

**Comment by h4xnoodle** [comment]
Hi @ichandan16

It seems there is an incompatibility issue here with vsphere.

A quick search led me to https://kb.vmware.com/s/article/2147078 which looks similar. Is there some setup you need to complete on your vsphere installation?

Bosh generally doesn't know anything about vsphere, and all interactions happen through the [vsphere CPI](https://github.com/cloudfoundry/bosh-vsphere-cpi-release). It may be helpful to file an issue there as well.

Rebecca, BOSH

**Comment by h4xnoodle** [comment]
Closing as this is a vsphere support issue. vsphere api 6.0+ is supported as per https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues/239
