### ISSUE TITLE
misc/ntp.yml doesn't update all ntp properties

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry/bosh-deployment#386]
After the change in 90f463c it looks like `cloud_provider/properties/ntp` and `instance_groups/0/properties/ntp`  blocks are not updated. After some discussion on Slack it looks like these to blocks shouldn't exist anymore and that the accepted way of setting the NTP servers is in the agent and the resource pool which are not even set in `bosh.yml`.

The ops file seems to be doing the correct thing to override the NTP servers if we need to provide our own NTP servers.

**Comment by aashah** [comment]
I made a commit that looks to resolve the inconsistency, https://github.com/cloudfoundry/bosh-deployment/commit/6bd09baed15fe6aa6ce3a7a7fd0ff7228ad26627.

Closing this issue.

Thanks for opening an issue on this!
- Aakash
