### ISSUE TITLE
NTP setting for bosh director

### ISSUE THREAD

**Issue by t2sa** [cloudfoundry/bosh-deployment#388]
The director NTP setting seems to be off by one level. Should be below bosh https://github.com/cloudfoundry/bosh-deployment/blob/dc06cf6fc05a518044d1c18da6c3d46bc4669cd0/bosh.yml#L161-L165 as per [documentation](https://bosh.io/docs/ntp-config/#configuring-ntp-servers-in-the-director-itself). Currently its at same level as bosh and don't see the value populate when creating the bosh director. Director gets set with 0.pool.ntp.org and 1.pool.ntp.org which am thinking are defaults.

**Comment by bgandon** [comment]
This is a good catch indeed. I've created #390 in order to fix this.
