### ISSUE TITLE
disable registry credentials display on ec2 instances - aws cpi 

### ISSUE THREAD

**Issue by jeswant** [cloudfoundry/bosh-deployment#406]
This is regarding the bosh director registry. The username and passwords are displayed in "user data" section on every EC2 instance.

**Display Location:** AWS > EC2 -> Instances -> select instance  -> Actions -> Instance Settings -> Edit user data

`{"registry":{"endpoint":"http://registry:password@10.229.0.8:25777"}}`

https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/cpi.yml#L47

**Edit user data example:** https://samkirkiles.svbtle.com/aws-amis-explained-changing-and-editing-user-data 

Can we avoid displaying registry credentials on ec2 instances?

Ref: https://bosh.io/docs/bosh-components/#registry
https://github.com/cloudfoundry/bosh/blob/master/spec/registry.yml.erb_spec.rb#L180

**Comment by voelzmo** [comment]
Hey @jeswant,

Thanks for raising this issue. It is absolutely possible and even recommended to remove the registry if you're using recent versions of the BOSH director and the AWS CPI. How are you installing your director? If you're using [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment), there is a specific ops-file you can use: https://github.com/cloudfoundry/bosh-deployment/blob/master/experimental/remove-registry.yml
If you're using another way to install the director, you can use the information in this ops-file to make the changes to your installation process yourself.

Hope that helps!

**Comment by jeswant** [comment]
@voelzmo Thank you!

After disabling the registry, tried the following to change the stemcell of an existing deployment:
`bosh -d logsearch deploy logsearch.yml --fix --recreate`  and it complains about the registry being disabled.
```
Task 464 | 15:41:03 | Updating instance elasticsearch_master: elasticsearch_master/ddf8d0f9-d53c-4362-87e2-181aa0a1e872 (0) (canary) (00:00:44)
          L Error: CPI error 'Bosh::Clouds::CloudError' with message 'An attempt to read registry settings has failed for instance_id=i-05af3310b495696d2. The registry is disabled.' in 'detach_disk' CPI method (CPI request ID: 'cpi-559099')
```
with that, I’m getting the impression that if I disable the registry on an environment that has deployments, the deployments may go unmanaged until I put the registry back. New deployments would work as expected.

Is it possible to keep the registry and make it HTTPS instead?

**Comment by voelzmo** [comment]
Hey @jeswant, just for completeness sake: which versions of BOSH director, AWS CPI and stemcell are you using? In theory, this error shouldn't happen, given this code in the AWS CPI: https://github.com/cloudfoundry/bosh-deployment/issues/406https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/d5c57fdd193ec1ba436b036e5f1bd22ffe70618f/src/bosh_aws_cpi/lib/cloud/aws/cloud_v2.rb#L100

**Comment by voelzmo** [comment]
You can find more information about the properties like `api_version` that are transmitted in this specific call in the debug log with 
```
bosh task 464 -- debug | grep 'cpi-559099'
```

The statement you're looking for is something like 
```
{"method":"#{method}","arguments":#{arguments.to_json},"context":{"director_uuid":"fake-director-uuid","request_id":"cpi-fake-request-id"},"api_version":#{cpi_api_version}}
```
