### ISSUE TITLE
vsphere cpi.yml

### ISSUE THREAD

**Issue by pcf-user** [cloudfoundry/bosh-deployment#407]
Hi - Are there any plans to update the stemcell to 621.99?

https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/cpi.yml

**Comment by voelzmo** [comment]
@mrosecrance This seems like a bug in automation, since all other CPIs got their update 2 days ago?

**Comment by mrosecrance** [comment]
Yep, that pipeline just took a while to go green

**Comment by pcf-user** [comment]
@mrosecrance : Thank you.
