### ISSUE TITLE
TLS handshake failures after CPI switch to storage.googleapis.com

### ISSUE THREAD

**Issue by lodener** [cloudfoundry/bosh-deployment#419]
On both our AWS and Azure environments, we are seeing TLS handshake failures when trying to download the bionic stemcell after the CPI switch to storage.googleapis.com (750bc6979dace8a7e357ab7a28a70a192604096a and dd53657d25b9afcf809473eb62f3fe63741e60c7):

```
Started validating
  ...
  Downloading stemcell... Failed (00:00:01)
Failed validating (00:00:14)

Failed to download from 'https://storage.googleapis.com/bosh-core-stemcells/1.10/bosh-stemcell-1.10-azure-hyperv-ubuntu-bionic-go_agent.tgz':
  Unable to download:
    Performing GET request:
      Get "https://storage.googleapis.com/bosh-core-stemcells/1.10/bosh-stemcell-1.10-azure-hyperv-ubuntu-bionic-go_agent.tgz": remote error: tls: handshake failure
```

```
Started validating
  ...
  Downloading stemcell... Failed (00:00:01)
Failed validating (00:00:50)


Failed to download from 'https://storage.googleapis.com/bosh-aws-light-stemcells/1.10/light-bosh-stemcell-1.10-aws-xen-hvm-ubuntu-bionic-go_agent.tgz':
  Unable to download:
    Performing GET request:
      Get "https://storage.googleapis.com/bosh-aws-light-stemcells/1.10/light-bosh-stemcell-1.10-aws-xen-hvm-ubuntu-bionic-go_agent.tgz": remote error: tls: handshake failure
```
Simply curling these files straight from the container (using either TLSv1.1, TLSv1.2 or TLSv1.3) works without issue.
Reverting back to the amazonaws.com URL also works without issue.

**Comment by benjaminguttmann-avtq** [comment]
Hi @lodener maybe related to this one => https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-bionic%2Fv1.10 

`if you encounter the issue 'remote error: tls: handshake failure' you should upgrade your bosh cli to 6.4.4 or higher`

**Comment by lodener** [comment]
Ah good one, that seems to have solved it.
We were still on 6.4.3, and after upgrading to 6.4.4 the issue no longer occurs.

Thanks @benjaminguttmann-avtq!
