### ISSUE TITLE
bosh-dns (?) certificate expirted

### ISSUE THREAD

**Issue by jeseen** [cloudfoundry/bosh-deployment#421]
Hi,
Our bosh certs were expired, so we followed this procedure to recreate all certificates: https://bosh.io/docs/nats-ca-rotation/#expired
So we 
1. removed all certs in the certs.yml
2. did a `bosh create-env ... ` to update the director certs. So far so good.
3. tried to recreate the deployments (with --fix option) to apply the new certs
--> however, this last step fails, because the bosh-dns job logs keeps spitting this error: ERROR - Unable to configure health checker failed to load keypair: certificate has expired: validity ended at ...

Even a `bosh deploy --recreate` of this (minio bosh) deployment does not help. 

Any ideas on how to fix this would be appreciated.
Thanks

**Comment by benjaminguttmann-avtq** [comment]
Hi @jeseen , normally the bosh-dns is handled via the runtime-config. In a setup with credhub those certificates gets stored in credhub. In that case you should be able to find them with something like

`credhub get -n /dns_api_tls_ca` and `credhub get -n /dns_healthcheck_tls_ca
`

As your certificates already expired you can do a 'hard-rotation' here, that means you can create new ca certificates with

```
credhub regenerate -n /dns_api_tls_ca
credhub regenerate -n /dns_healthcheck_tls_ca
```

and afterwards regenerate all certificates that have been signed by those two CAs with

```
credhub bulk-regenerate --signed-by=/dns_api_tls_ca
credhub bulk-regenerate --signed-by=/dns_healthcheck_tls_ca
```

After that you can go ahead and deploy the deployment that is having issues with bosh-dns.

Beside that, for credhub stored certificates please check this guide => https://github.com/pivotal/credhub-release/blob/main/docs/ca-rotation.md
