### ISSUE TITLE
Creating vm: Machine Type 'n1-standard-1' does not exists

### ISSUE THREAD

**Issue by davidmehi** [cloudfoundry/bosh-deployment#427]
Hello, I ran the following bosh command to install in GCP.  However, I'm getting an error saying machine type n1-standard-1 does not exist.  However, I know that it is a valid machine type, so wondering what could be causing this?

>>bosh create-env bosh-deployment/bosh.yml     --state=state.json     --vars-store=creds.yml     -o bosh-deployment/gcp/cpi.yml     -v director_name=bosh-1     -v internal_cidr=10.0.0.0/24     -v internal_gw=10.0.0.1     -v internal_ip=10.0.0.6     --var-file gcp_credentials_json=~/bosh-1/boshops.key.json     -v project_id=xxxxx     -v zone=us-central1-a     -v tags=[internal]     -v network=default     -v subnetwork=default
Deployment manifest: '/root/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-google-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-google-cpi'... Finished (00:00:04)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:07)

Started installing CPI
  Compiling package 'golang-1-darwin/42353203720fdc244cc16f881167bb0363f38ff6f991247c4356e38bc6b5fb81'... Finished (00:00:00)
  Compiling package 'golang-1-linux/79f531850e62e3801f1dfa4acd11c421aebe653cd4316f6e49061818071bb617'... Finished (00:00:00)
  Compiling package 'bosh-google-cpi/3edd09f99e45b570edfdc901ff7ae839bc0df993a40ee32cc602e640f033787d'... Finished (00:00:00)
  Installing packages... Finished (00:00:11)
  Rendering job templates... Finished (00:00:00)
  Installing job 'google_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:12)

Uploading stemcell 'bosh-google-kvm-ubuntu-bionic-go_agent/1.41'... Finished (00:00:00)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'https://www.googleapis.com/compute/v1/projects/cloud-foundry-310819/global/images/stemcell-1-41-google-kvm-ubuntu-bionic-1639044401'... Failed (00:00:00)
Failed deploying (00:00:00)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'https://www.googleapis.com/compute/v1/projects/cloud-foundry-310819/global/images/stemcell-1-41-google-kvm-ubuntu-bionic-1639044401':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating vm: Machine Type 'n1-standard-1' does not exists: \u003cnil cause\u003e","ok_to_retry":false}

Exit code 1

**Comment by beyhan** [comment]
Hi @davidmehi,

this looks like to be related to the GCP CPI https://github.com/cloudfoundry/bosh-google-cpi-release. I would suggest you to close this one and open another issue in the GCP CPI repository. Could you also try to create a `n1-standard-1` VM from the GCP Console in the same region as you tried with bosh?

**Comment by davidmehi** [comment]
Thanks @beyhan, I will open a ticket there.  I am able to create a n1-standard-1 VM in the console and gcloud, so I'm thinking it's a missing some configuration when calling the GCP API.

**Comment by davidmehi** [comment]
Opened [issue](https://github.com/cloudfoundry/bosh-google-cpi-release/issues/330) to the bosh-google-cpi-release repo
