### ISSUE TITLE
Google storage for stemcells nor reachable from AWS China accounts

### ISSUE THREAD

**Issue by flaviomoringa** [cloudfoundry/bosh-deployment#428]
Since the change to use Google Storage to retrieve the stemcell images in "aws/cpi.yml" in line 14 we are not able to use them when deploying on our AWS China (Beijing) account. 

To make it work we have to replace the current stemcell with the last one available on AWS, which was https://bosh-aws-light-stemcells.s3-accelerate.amazonaws.com/1.1/light-bosh-stemcell-1.1-aws-xen-hvm-ubuntu-bionic-go_agent.tgz

This means we are stuck with that version without all the security updates of the latest versions.

Could it be possible to at least make sure to keep updating the AWS endpoint at https://bosh-aws-light-stemcells.s3-accelerate.amazonaws.com with the latest stemcells?

That way we would still need to change the url by hand, but the latest stemcells would always be available in the aws s3 endpoint.

Thanks

**Comment by flaviomoringa** [comment]
It seems that what is needed is to make sure the AMI's needed are also added to the china region cn-north-1.

I can see on the current stemcells that region is not there.

If it returns an AMI id it means it’s available, if not it won’t. Example:
 
curl -s -L https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-bionic-go_agent\?v\=1\.51 | tar -xzOf- stemcell.MF | grep cn-north-1 | awk '{print $2}'
 
curl -s -L https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-bionic-go_agent\?v\=1\.10 | tar -xzOf- stemcell.MF | grep cn-north-1 | awk '{print $2}'
 
curl -s -L https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-bionic-go_agent\?v\=1\.1 | tar -xzOf- stemcell.MF | grep cn-north-1 | awk '{print $2}'
ami-0606f87d13023bd1b

As you can see only the 1.1 version is available in the china region we need.

**Comment by rkoster** [comment]
@flaviomoringa, unfortunately, we no longer have an legal entity (previously the Pivotal entity was used). Because of this we can no longer publish lite stemcells for the China region.

**Comment by flaviomoringa** [comment]
@rkoster that is quite unfortunate... Can't VMWare help with this? We are using VMWare Tanzu, so maybe we can ask them to help with this somehow?

**Comment by rkoster** [comment]
VMWare Tanzue is not using the bionic stemcell right?

**Comment by rkoster** [comment]
But yeah raising this issue with your VMware account representative could help the product people prioritize this feature request.

**Comment by flaviomoringa** [comment]
@rkoster not sure if they are using the bionic one, but at least we are in our concourse deployments to manage VMWare Tanzu's PCF version we use. I have already raised this issue with them, let's see what will happen.

Thanks for your help.
