### ISSUE TITLE
Using bosh create-env got error: connect: no route to host

### ISSUE THREAD

**Issue by ElioZhou** [cloudfoundry/bosh-deployment#429]
Hello team,
When I use Bosh create-env I am getting this error, does anyone know how to solve this?
![image](https://user-images.githubusercontent.com/41265059/152475396-ae0e7982-ad09-48f7-83a3-8fbbb17ab538.png)

The configuration is

>     -v internal_cidr=10.0.0.0/8 [\](url)
>     -v internal_gw=10.0.0.1 \
>     -v internal_ip=10.0.0.14 \

And I have set my virtual network address space to 10.0.0.0/8
![image](https://user-images.githubusercontent.com/41265059/152475465-effd87ea-6974-4349-add6-9aac3abcaa25.png)

**Comment by beyhan** [comment]
Hi @ElioZhou,
from where do you execute the `create_env` command? Is it a VM in the Same VN?

**Comment by ElioZhou** [comment]
> Hi @ElioZhou, from where do you execute the `create_env` command? Is it a VM in the Same VN?

I execute this command from a VM of Azure with VN shown below
![image](https://user-images.githubusercontent.com/41265059/152578535-335d68a7-3619-4e98-a7fe-2163649626f1.png)
and the VN I set in the command parameter is shown below
![image](https://user-images.githubusercontent.com/41265059/152578787-6a3dec83-39df-4896-8ade-5222806cd80e.png)
![image](https://user-images.githubusercontent.com/41265059/152578344-9b68cb3a-c95f-4793-aa5d-099494236341.png)

And this time it gave me this error
![image](https://user-images.githubusercontent.com/41265059/152578857-03702a9c-f958-45fd-8cc9-e900680e2f12.png)

**Comment by rkoster** [comment]
i/o timeout usually means you have not configured your firewall rules correctly. Please verify the IP is reachable on 6868 from the instance where you are running `bosh create-env` from.
