### ISSUE TITLE
properties.director.db.listen_address is invalid

### ISSUE THREAD

**Issue by dennisjbell** [cloudfoundry/bosh-deployment#441]
https://github.com/cloudfoundry/bosh-deployment/blob/a00286ed3d095944b34c56f76b70c6be4e89e97e/bosh.yml#L74

director.db.listen_address is [not defined in the job spec](https://github.com/cloudfoundry/bosh/blob/main/jobs/director/spec#L289-L326), going all the way back to 2016.

it is a valid property for the embedded [postgres](https://github.com/cloudfoundry/bosh/blob/185f183817380a4acf4d0201226d132033941368/jobs/postgres/spec#L21) job, but not applicable to the director.

**Comment by rkoster** [comment]
@dennisjbell would you be so kind and create a PR to address this?

**Comment by mvach** [comment]
Here the required PR: https://github.com/cloudfoundry/bosh-deployment/pull/442
