### ISSUE TITLE
Changing Cloud-config.yml to update one zone in a 2 zone deployment causes a full deploy.

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/bosh-deployment#447]
We performed a live disaster recovery exercise recently in one of our test regions. The failure we tested was the failure of one zone in AWS in our 2 zone deployment. We simulated this by terminating all of the instances in the second zone (as described in the cloud-config).

We updated the cloud-config for z2 to a new zone with the attendant subnet changes and applied it with `bosh update-cloud-config` and ran the deployment. We were surprised to find that the deploy started by replacing all of the z1 instances before moving to z2. In this small test region, we only had 2 zones running, and so this deployment caused unexpected downtime.

Is a full deployment expected when a cloud-config change is made, even though the change only impacts a subset of instances? Is there a way to avoid or shorten this downtime?

**Comment by beyhan** [comment]
The bosh behaviour around this is documented in https://bosh.io/docs/azs/#adding-and-removing-azs-to-a-deployment. It shouldn't touch z1 actually. Wasn't there any other change? Could you try and provide some sample and executed steps.

**Comment by pusherofbrooms** [comment]
There weren't any other changes outside the necessary changes in cloud-config to move to the new subnet. We saw this behavior in our informal testing region and our formal test region, so I don't think it was a fluke.

We don't have any further DR testing scheduled for at least the next six months sadly.

**Comment by rkoster** [comment]
@pusherofbrooms could you provide some cloud-config snippets of the cloud-config before and after the recovery?
