### ISSUE TITLE
Review the VM and disk types used in the cloud-configs

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-deployment#451]
We should review the VM and disk types we use in our cloud-configs and use more up-to-date options which could be potentially with better performance and cheaper.

Input to this is the [great talk by David Stevenson](https://cfday2022.sched.com/event/1ArSi/how-we-modernized-and-reduced-the-infrastructure-costs-for-running-cf-david-stevenson-vmware) from CF Day 2022 and [cloud-configs used in bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader/blob/main/cloudconfig/).

**Comment by rkoster** [comment]
It looks like bosh-deployment was already updated: https://github.com/cloudfoundry/bosh-deployment/commit/c8969609ef77ec5debee04cee4efed038bc69eac

**Comment by beyhan** [comment]
The recommended new instance types are described in the community RFC [rfc-0009-efficient-modern-vm-sizes](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0009-efficient-modern-vm-sizes.md). E.g. we use for GCP [n1-standard-2](https://github.com/cloudfoundry/bosh-deployment/blob/d8f9b3ce03e306c6fd0aa824741d541e654ff48c/gcp/cloud-config.yml#L12-L22) which should be replaced by `e2-medium` according to the RFC. If we agree to follow the RFC I can provide the pr.
