### ISSUE TITLE
certificate  validity increase

### ISSUE THREAD

**Issue by spkrsna** [cloudfoundry/bosh-deployment#452]
now by default if we are redeploying or rotating certificate it is valid for one year from the rotating date , example if we are rotating on 26th June 2023 then new certificate we will valid for 25th June 2024 

How to increase the validity to above 2years or more while rotating

**Comment by beyhan** [comment]
Please use the ops files provided in https://github.com/cloudfoundry/bosh-deployment/tree/master/misc/certificate-duration to configure the certificate duration.
