### ISSUE TITLE
Failed at Creating VM for instance 'bosh/0' from stemcell

### ISSUE THREAD

**Issue by ISHGARD-2** [cloudfoundry/bosh-deployment#458]
hello, i'm newbee and i got trapped here. should i ask for help here? could anyone tell me what's wrong with this, thank u.

root@ishgard-vm:~/bosh-1# bosh create-env bosh-deployment/bosh.yml     --state=state.json     --vars-store=creds.yml  -o bosh-deployment/vsphere/cpi.yml     -v director_name=bosh-1     -v internal_cidr=192.168.1.1/24 -v internal_gw=192.168.1.1 -v internal_ip=192.168.1.253 -v network_name="VM Network"     -v vcenter_dc=Datacenter -v vcenter_ds=datastore1 -v vcenter_ip=192.168.1.252 -v vcenter_user=administrator@vsphere.local     -v vcenter_password=1029384756CAOdi@ -v vcenter_templates=bosh-1-templates     -v vcenter_vms=bosh-1-vms     -v vcenter_disks=bosh-1-disks     -v vcenter_cluster=PaaS
Deployment manifest: '/root/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:00)
  Downloading release 'bosh-vsphere-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:02)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:08)
Finished validating (00:00:12)

Started installing CPI
  Compiling package 'golang-1-darwin/c763ba92134af1d637bb6790f12453f1f9f15c1ec47bf79b0ec96de6814aa81b'... Finished (00:00:10)
  Compiling package 'golang-1-linux/29f2024e7d815be0694944c3c3c9512914a36a31d5fa1b2cbd2452c8d331ce90'... Finished (00:00:10)
  Compiling package 'ruby-3.1/8b225e7cc2608305a7b784b5828b2b4b7c7adc3eb14af46e313d64a9e14a3ad6'... Finished (00:02:10)
  Compiling package 'iso9660wrap/57da6c48c387379cc701856daa68f9f5269c2441d0195a0c5a735c93d6d2c489'... Finished (00:00:07)
  Compiling package 'vsphere_cpi/3a52a41dfcd0bdf411198f93e6a89591553be6afda07780d6de7df7d13dc2ddb'... Finished (00:00:16)
  Installing packages... Finished (00:00:04)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:03:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-jammy-go_agent/1.207'... Finished (00:01:27)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-4108a43e-1ff8-447d-81a1-c16a16561996'... Failed (00:00:10)
Failed deploying (00:00:10)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-4108a43e-1ff8-447d-81a1-c16a16561996':
        Unexpected external CPI command result: '[]interface {}{"vm-34e0278a-dfd4-4b71-a083-62c26f30542b", map[string]interface {}{"default":map[string]interface {}{"default":[]interface {}{"dns", "gateway"}, "dns":[]interface {}{"8.8.8.8"}, "gateway":"192.168.1.1", "ip":"192.168.1.253", "netmask":"255.255.255.0", "type":"manual", "cloud_properties":map[string]interface {}{"name":"VM Network"}}}}'

Exit code 1

**Comment by jpalermo** [comment]
That's a very strange error. It seems like the `bosh` cli and the vsphere cpi were expecting different things from the `create_vm` CPI command.

The interface between these components hasn't changed in quite some time though...

What version of the bosh cli are you using? And are you using the current `master` branch of the `bosh-deployment` repo?

**Comment by ISHGARD-2** [comment]
> That's a very strange error. It seems like the `bosh` cli and the vsphere cpi were expecting different things from the `create_vm` CPI command.
> 
> The interface between these components hasn't changed in quite some time though...
> 
> What version of the bosh cli are you using? And are you using the current `master` branch of the `bosh-deployment` repo?

yes! my bosh-cli (ver 3.1.0) was out of date. i change it to ver 7.4.0 and it worked out. thank u!
