### ISSUE TITLE
Please Externalize NTP and DNS as variables

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/bosh-deployment#469]
Most enterprises don't use google dns, and they'll use their own.  Homelabs are in the same boat.

Removing the ops file (https://github.com/cloudfoundry/bosh-deployment/blob/master/local-dns.yml) removes the ability to replace the DNS.

https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml#L139
https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml#L45-L48
https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml#L164-L167

**Comment by haydonryan** [comment]
Also the refernce on 

> local-dns.yml: Enables Director DNS beta functionality

https://github.com/cloudfoundry/bosh-deployment/tree/master?tab=readme-ov-file refers to an empty opsfile.

**Comment by jpalermo** [comment]
The local-dns ops file never allowed override of dns servers. It was used to enable the [local_dns](https://github.com/cloudfoundry/bosh/blob/main/jobs/director/spec#L184) feature of bosh. You can see the old version of it [here](https://github.com/cloudfoundry/bosh-deployment/commit/b4abd3412b48687cd31b774d3ab48975e44c28f7)

There is an existing ops-file to replace the dns entries here: https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/dns.yml

And the one to replace ntp values is here: https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/ntp.yml

Typically empty ops-file are kept around when values are incorporated into defaults so people who have pipelines or tooling using those scripts don't see those things break as we make changes.

**Comment by haydonryan** [comment]
Ahh that makes sense on the local_dns and empty ops files.  

I'm coming back from a hiatus to an implementation role.  I assume PR for documentation updates is welcome?

**Comment by beyhan** [comment]
>I assume PR for documentation updates is welcome?

yes, this is very welcome :-)

**Comment by haydonryan** [comment]
Reopening to attach to PR

**Comment by jpalermo** [comment]
Closing as the PR was merged. Thanks!
