### ISSUE TITLE
bosh-lite director not persistent across reboot

### ISSUE THREAD

**Issue by vchrisb** [cloudfoundry/bosh-deployment#47]
I've successfully deployed bosh-lite on virtualbox but after reboot, the bosh director is failing.
SSHing into to VM indicates that monit is not running and even after manually starting it, many service are not initializing.
Is this expected? I've seen comments, that bosh deployments are not persistent across reboots on bosh-lite but I haven't seen such a comment regarding the director.
Thx!

**Comment by cppforlife** [comment]
@vchrisb we currenlty dont support reboot with virtualbox cpi because there is an agent problem. we have plans to fix it though. currently you can rerun bosh create-env with same args and it will bring it back.

**Comment by vchrisb** [comment]
thank you @cppforlife
