### ISSUE TITLE
Fresh virtualbox deployment incorrectly configures time

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/bosh-deployment#49]
We've followed the instructions in the README to create a new Bosh Lite on VirtualBox.

The created VM has incorrectly configured its time. It's erroneously taken the host machine's time (e.g., 9:30am MDT) as the VM's UTC time (e.g., 9:30am UTC).

**Comment by cppforlife** [comment]
sounds like you may want to configure ntp servers?

**Comment by jtarchie** [comment]
@cppforlife, we are following instructions for [vbox](https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md). Are you able to lead us in right direction to solve this issue? It keeps effecting us.

**Comment by cppforlife** [comment]
> Are you able to lead us in right direction to solve this issue?
have you tried setting ntp servers as suggested above.

**Comment by cppforlife** [comment]
@jtarchie was this resolved?

**Comment by enocom** [comment]
@cppforlife After filing this issue, I noticed we were one minor version under what the docs suggestion, i.e., 5.0 instead of 5.1. Do you think the proper minor version or VirtualBox will resolve this time problem?

**Comment by apoydence** [comment]
We tested on the newest version of VirtualBox (i.e., 5.1.20) and saw no problems with the time settings.

**Comment by cppforlife** [comment]
interesting, thx for an update
