### ISSUE TITLE
Interpolating gcp_credentials_json for GCP provider

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry/bosh-deployment#52]
Probably because I'm bad at bash, but I had a tough time getting `gcp_credentials_json` to interpolate. Assuming your creds JSON is in an env var named `GOOGLE_CREDENTIALS`, this is how you do it:

```
bosh create-env ~/dev/bosh/workspaces/bosh-1/bosh.yml \
 -v gcp_credentials_json=\'"$GOOGLE_CREDENTIALS"\' \
...
```

I'm working on docs for all of this on GCP and will include this there.

**Comment by cppforlife** [comment]
@evandbrown i typically end up clicking download button from portal and use `--var-file gcp_credentials_json=~/Downloads/something.json`. alternatively you can use env vars directly:

```
export BOSH_gcp_credentials_json=$GOOGLE_CREDENTIALS
bosh create-env ~/dev/bosh/workspaces/bosh-1/bosh.yml ... --vars-env BOSH
```

**Comment by evandbrown** [comment]
Ahh, `--vars-env`. Brilliant! Thanks, @cppforlife.
