### ISSUE TITLE
maybe mismatch between sourcecode and docs ?

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry/bosh-deployment#54]
I think this deployment set is made for bosh manifest version 2.
(i'm not sure)

Anyway, I see **varaibles** block from 109 line in **bosh.yml** file which is not described in published documents: https://bosh.io/docs/manifest-v2.html

maybe the document should be updated.

**Comment by cppforlife** [comment]
@kukgini we havent yet finished documenting cli v2 features. manifest v2 is a different set of features that were implemented over a year ago.

**Comment by cppforlife** [comment]
Updated manifest v2 doc and added CLI Variable interpolation: https://bosh.io/docs/cli-int.html. Will also add docs about config server / credhub when we cut v262 bosh release.
