### ISSUE TITLE
Please link documentation to `replace` mechanism

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh-deployment#57]
Could you please link https://github.com/cppforlife/go-patch/blob/master/docs/examples.md in your documentation here to elaborate on the `-o` flag?
Instead of letting people reverse-engineer to extend this repository, it would be great to know what syntax is allowed.

**Comment by cppforlife** [comment]
Added http://bosh.io/docs/cli-ops-files. Will update readme here for reference.
