### ISSUE TITLE
Use ((internal_ip)) for dns.address in powerdns.yml

### ISSUE THREAD

**Issue by WarheadsSE** [cloudfoundry/bosh-deployment#59]
https://github.com/cloudfoundry/bosh-deployment/blob/master/powerdns.yml#L17

Deployed VMs (in my case, CloudFoundry from an existing and functional manifest) will have their primary resolver set to 127.0.0.1. To get a properly functioning system, i needed to change this to the `((internal_ip))` provided during deployment.

I might suggest considering an option to provide `dns_domain_name` as a variable interpolation as well.

**Comment by cppforlife** [comment]
> i needed to change this to the ((internal_ip)) provided during deployment.

merged.

> I might suggest considering an option to provide dns_domain_name as a variable interpolation as well.

will be covered in upcoming local dns work.
