### ISSUE TITLE
Persistent disks not working in garden containers.

### ISSUE THREAD

**Issue by htrmeira** [cloudfoundry/bosh-deployment#78]
Steps to reproduce the problem:
- Deploy a bosh release with a persistent disk.
- Create any file inside /var/vcap/store 
- Update the deployment manifest and deploy it again.
- The file inside /var/vcap/store has vanished

It is also possible to notice that the content of /var/vcap/store inside the instance is different from the one inside the bosh VM (/var/vcap/store/warden_cpi/persistent_bind_mounts_dir/:uuid/:uuid)

I am using bosh-deployment with Virtual Box version 5.1.22r115126.

Deployed using the latest version of bosh-deployment (latest commit 01bf99ccda147f7925ef935010dd9124b9f90cc1) with the following command:

```
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state ./state.json \
  -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
  -o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
  -o ~/workspace/bosh-deployment/bosh-lite.yml \
  -o ~/workspace/bosh-deployment/bosh-lite-runc.yml \
  -o ~/workspace/bosh-deployment/jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork
```

**Comment by cppforlife** [comment]
Dup of https://github.com/cppforlife/bosh-warden-cpi-release/issues/5

**Comment by htrmeira** [comment]
Hi, 
This is fixed with the new warden version. I think this issue can be closed.
