### ISSUE TITLE
Openstack (Mitaka) expects tenant instead of project

### ISSUE THREAD

**Issue by keshto** [cloudfoundry/bosh-deployment#87]
With Openstack (Mitaka) the cpi complains about missing `tenant` key. It appears openstack has enforced using `tenant` rather than having it interchangeable with `project`. There has to be some logic to change https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/cpi.yml#L72 to be `tenant: ((openstack_tenant))` and relevant docs. If that works for older versions of openstack this should just be the default, but older versions of openstack need to be tested first.

**Comment by dpb587-pivotal** [comment]
Try the [openstack/keystone-v2.yml](https://github.com/cloudfoundry/bosh-deployment/blob/d0af57984e526941e7ea937673a45c3da8924458/openstack/keystone-v2.yml) ops file - it uses the variable `openstack_tenant`.

**Comment by cppforlife** [comment]
@keshto did that ops file work for you?

**Comment by keshto** [comment]
Did not get to test, but the keystone-v2 ops file looks like it should work. Maybe a note, if it does not already exist, to the openstack install doc would be helpful.
