### ISSUE TITLE
BOSH lite instructions do not work

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-deployment#92]
- MacOS 10.12.5
- VirtualBox 5.1.22
- `bosh-cli` v2.0.26 installed from Homebrew
- cloned this repo, on `master` (commit https://github.com/cloudfoundry/bosh-deployment/commit/bedbfc9bbf15df64fb9e34343b3a18995d4ca709)

Followed instructions for [BOSH Lite on VirtualBox](https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md), I get as far as step 4:

```bash
bosh -e 192.168.50.6 --ca-cert <(bosh int ./creds.yml --path /director_ssl/ca) alias-env vbox
```
which errors with
```
Exected URL '%!!(MISSING)s(<nil>)' to be a string

Exit code 1
```

**Comment by cppforlife** [comment]
is this something that started happening with new cli?

**Comment by Freyert** [comment]
Instructions in the documentation are different than that:

`bosh alias-env vbox -e 192.168.50.6 --ca-cert <(bosh int ./creds.yml --path /director_ssl/ca)`

Documentation on VirtualBox CloudConfig is sorely lacking.

**Comment by h4xnoodle** [comment]
We are hoping by now this issue has been resolved. Closing.
