### ISSUE TITLE
Docker CPI - Cannot upload stemcell due to "Cannot connect to the Docker daemon... Is the docker daemon running?"

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/bosh-deployment#94]
Hello,

Please note that this issue has nothing in common with #93.

I was able to run the bosh director on docker by using the ``unix socket`` approach. The sample procedure is [here](https://github.com/cloudfoundry/bosh-deployment/blob/master/test.sh#L435) and I confirm that it works fine.

I was able to target my director and then log-in successfully. However, when I tried to upload warden stemcell I got the following result:

```
#
# With this I confirmed that my bosh director is in good health.
#
[mycomp@homeoffice cloudfoundry]$ bosh2 -e docker vms
Using environment '10.245.0.10' as client 'admin'

Succeeded

#
# Just in case, I checked if the docker container is running and it seems it's fine.
#
[mycomp@homeoffice cloudfoundry]$ docker ps
CONTAINER ID        IMAGE                                                    COMMAND                   CREATED             STATUS              PORTS                                                                                                                                                                           NAMES
7d88343a66c6        bosh.io/stemcells:d974cae3-658a-4220-56dd-2791573cceb7   "bash -c '\n      u..."   11 minutes ago      Up 11 minutes       0.0.0.0:32802->22/tcp, 0.0.0.0:32801->4222/tcp, 0.0.0.0:32800->6868/tcp, 0.0.0.0:32799->8080/tcp, 0.0.0.0:32798->8443/tcp, 0.0.0.0:32797->25250/tcp, 0.0.0.0:32796->25555/tcp   e07c76c7-54b1-48ce-7f16-d6623b7ae4b1

#
# Now I try to upload warden stemcell and I get the error below.
#
[mycomp@homeoffice cloudfoundry]$ bosh2 -e docker upload-stemcell bosh-warden-stemcell-3421.6.tgz
Using environment '10.245.0.10' as client 'admin'

######################################################### 100.00% 240.32 MB/s 1s
Task 4

16:40:06 | Update stemcell: Extracting stemcell archive (00:00:02)
16:40:08 | Update stemcell: Verifying stemcell manifest (00:00:00)
16:40:08 | Update stemcell: Checking if this stemcell already exists (00:00:00)
16:40:08 | Update stemcell: Uploading stemcell bosh-warden-boshlite-ubuntu-trusty-go_agent/3421.6 to the cloud (00:00:00)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Importing stemcell from '/var/vcap/data/tmp/director/stemcell20170626-1864-1yudoue/image': Starting image import: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?' in 'create_stemcell' CPI method

16:40:08 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Importing stemcell from '/var/vcap/data/tmp/director/stemcell20170626-1864-1yudoue/image': Starting image import: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?' in 'create_stemcell' CPI method

Started  Mon Jun 26 16:40:06 UTC 2017
Finished Mon Jun 26 16:40:08 UTC 2017
Duration 00:00:02

Task 4 error

Uploading stemcell file:
  Expected task '4' to succeed but state is 'error'

Exit code 1
```

The error I get is this one:

**Error: CPI error 'Bosh::Clouds::CloudError' with message 'Importing stemcell from '/var/vcap/data/tmp/director/stemcell20170626-1864-1yudoue/image': Starting image import: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?' in 'create_stemcell' CPI method**

I am in doubt how to approach this issue because I know for sure that my docker daemon is running just fine. Could you please assist me and point me to the possible root cause of the issues that I need to investigate? Thank you!

Regards,
Ivan Davidov

**Comment by ivandavidov** [comment]
Just checked - my docker container which contains the bosh director seems to be working in privileged mode which I guess is expected:

```
[mycomp@homeoffice cloudfoundry]$ docker inspect --format='{{.HostConfig.Privileged}}' 7d88343a66c6
true
```

**Comment by cppforlife** [comment]
@ivandavidov yup, this error is due to wrong perms on the .sock file. given that sock is bind mounted perms from outside and inside the container must make sense to the user of the sock file. inside the container it expects that vcap user can access it. im not quite sure yet what to do aside from chowing sock file on cpi startup.

**Comment by ivandavidov** [comment]
Thank you! Even though it may not be the best way to approach this, I temporarily changed the ``/var/run/docker.sock`` permissions to 'rw' for all users. I'll update the issue as soon as I have the time to test if this fixes the problem.

**Comment by ivandavidov** [comment]
It's been confirmed that the stemcell can be uploaded once the permissions of  ``/var/run/docker.sock`` are changed to less restrictive. Thank you for the assistance on this matter. The issue is resolved (for now) and I'm closing it.

Regards,
Ivan Davidov

**Comment by chewfred** [comment]
@ivandavidov How did you get it to work, i try to change it to 777 for that file and it did not work
